// @generated by scripts/vendor_free_tools.sh — DO NOT EDIT.
// Source of truth: faro-core/core-free/src/. Edit there and re-run the script;
// the core-sync CI job fails if this vendored copy drifts.

//! The normalized output envelope (`SkillResult`).
//!
//! Canonical definition of the contract in
//! `docs/skill-layer/01-output-envelope.md`. Every skill, every host binding,
//! every vendor returns this shape. The Python service mirrors these as Pydantic
//! models and a round-trip test keeps the two in sync.
//!
//! Serde is configured so the wire JSON matches the spec exactly: `status` is the
//! single discriminator and exactly one of `result` / `error` / `needs_input` is
//! present (the absent ones are omitted, not null).

use serde::{Deserialize, Serialize};

/// Current envelope schema version. Additive changes (new optional fields, new
/// `error.code` values, new `result.kind` variants) do not bump this; removals or
/// shape changes do.
pub const ENVELOPE_VERSION: &str = "1";

/// Top-level status discriminator. Values match faro-api's invocation envelope
/// (`success` / `failed`) so the whole platform speaks one status vocabulary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Status {
    Success,
    Failed,
    NeedsInput,
}

/// The kind of a successful result body.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ResultKind {
    Information,
    File,
    Files,
}

/// Closed set of buyer-safe error codes. Extend additively only.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    InvalidInput,
    Auth,
    RateLimited,
    InsufficientCredits,
    NotFound,
    Timeout,
    UpstreamFailed,
    Internal,
}

/// A single binary output, mirroring `upload_output()` in the worker. No base64
/// ever travels in the envelope.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileRef {
    pub download_url: String,
    pub mime: String,
    pub size_bytes: u64,
    pub filename: String,
    /// ISO-8601, or null (R2 lifecycle governs deletion, not a signed TTL).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
}

/// A provenance entry: the canonical home for citations / source links, so every
/// information result exposes sources in the same place regardless of skill.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Source {
    pub url: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

/// The `result` sub-object, present iff `status == success`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResultBody {
    pub kind: ResultKind,
    /// One-line natural-language recap. Off by default (opt-in per skill); never
    /// leaks vendor/technique.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// `kind == information`: the typed payload. ALWAYS a JSON object (scalars and
    /// arrays are wrapped as `{"value": ...}`) so the data lives under a single
    /// predictable key with a per-skill schema.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    /// Canonical provenance slot (citations, source URLs), shared by every skill.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<Source>>,
    /// `kind == file`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file: Option<FileRef>,
    /// `kind == files`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub files: Option<Vec<FileRef>>,
}

/// The `error` sub-object, present iff `status == failed`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrorBody {
    pub code: ErrorCode,
    /// Already `sanitize_error()`'d: no vendor URL/host/body.
    pub message: String,
    pub retryable: bool,
}

/// The `needs_input` sub-object, present iff `status == needs_input`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NeedsInput {
    pub question: String,
    /// Intent fields the skill could not default.
    pub missing: Vec<String>,
}

/// Normalized, buyer-safe metadata. Buyer-safe by construction — no slot for
/// vendor cost, margin, model id, raw tool name, or provider identity.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Meta {
    /// Credits actually billed; safe to surface (price transparency). May be
    /// fractional (1 credit = $0.001).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub credits_charged: Option<f64>,
    /// The price we expected to charge (pre-execution estimate).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub credits_estimated: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latency_ms: Option<u64>,
    /// Skill-prefix context-cache hit (a cost signal), not a result cache.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cached: Option<bool>,
    /// ISO-8601 timestamps (present for server invocations; absent for free/local).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<String>,
}

/// The full `SkillResult` envelope.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillResult {
    #[serde(rename = "faro_envelope")]
    pub envelope: String,
    /// Invocation id (present for billed/server calls; absent for free/local tools).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Caller idempotency key, echoed back when present.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    /// A signed continuation token (Spec 5 §7): self-contained chain state the caller
    /// echoes back to stay on-context and on-budget. Sits alongside `idempotency_key`;
    /// minted by the agent on a quote or a completed run, absent otherwise.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub continuation: Option<String>,
    /// `<namespace>.<skill-or-tool>`; safe to surface.
    pub skill: String,
    pub status: Status,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<ResultBody>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ErrorBody>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub needs_input: Option<NeedsInput>,
    pub meta: Meta,
}

/// Guarantee an information payload is a JSON object, so `result.data` always has
/// the same predictable shape. Non-objects are wrapped as `{"value": ...}`.
fn ensure_object(data: serde_json::Value) -> serde_json::Value {
    if data.is_object() {
        data
    } else {
        serde_json::json!({ "value": data })
    }
}

/// Detect a worker/tool file output ({download_url|url, mime, ...}) and map it to a
/// `FileRef`. Returns None for plain information payloads.
fn detect_file(payload: &serde_json::Value) -> Option<FileRef> {
    let obj = payload.as_object()?;
    let url = obj
        .get("download_url")
        .or_else(|| obj.get("url"))
        .and_then(|v| v.as_str())?;
    let mime = obj.get("mime").and_then(|v| v.as_str())?;
    let filename = obj
        .get("filename")
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
        .unwrap_or_else(|| url.rsplit('/').next().unwrap_or("file").to_string());
    Some(FileRef {
        download_url: url.to_string(),
        mime: mime.to_string(),
        size_bytes: obj.get("size_bytes").and_then(|v| v.as_u64()).unwrap_or(0),
        filename,
        expires_at: obj.get("expires_at").and_then(|v| v.as_str()).map(|s| s.to_string()),
    })
}

/// Lift a `sources`/`citations` list out of the payload into the canonical
/// `sources` slot. Conservative: only lifts list items that are URL strings or
/// `{url, title?}` objects; otherwise the field is left in the data untouched.
fn split_sources(payload: serde_json::Value) -> (serde_json::Value, Option<Vec<Source>>) {
    let mut obj = match payload {
        serde_json::Value::Object(m) => m,
        other => return (ensure_object(other), None),
    };
    for key in ["sources", "citations"] {
        let Some(serde_json::Value::Array(items)) = obj.get(key) else { continue };
        if items.is_empty() {
            continue;
        }
        let mut sources = Vec::with_capacity(items.len());
        let mut ok = true;
        for item in items {
            match item {
                serde_json::Value::String(s) => sources.push(Source { url: s.clone(), title: None }),
                serde_json::Value::Object(o) => match o.get("url").and_then(|v| v.as_str()) {
                    Some(u) => sources.push(Source {
                        url: u.to_string(),
                        title: o.get("title").and_then(|v| v.as_str()).map(|s| s.to_string()),
                    }),
                    None => {
                        ok = false;
                        break;
                    }
                },
                _ => {
                    ok = false;
                    break;
                }
            }
        }
        if ok {
            obj.remove(key);
            return (serde_json::Value::Object(obj), Some(sources));
        }
    }
    (serde_json::Value::Object(obj), None)
}

impl SkillResult {
    fn base(skill: impl Into<String>, status: Status) -> Self {
        Self {
            envelope: ENVELOPE_VERSION.to_string(),
            id: None,
            idempotency_key: None,
            continuation: None,
            skill: skill.into(),
            status,
            result: None,
            error: None,
            needs_input: None,
            meta: Meta::default(),
        }
    }

    /// `status: success` with structured information. `data` is normalized to a JSON
    /// object (scalars/arrays are wrapped as `{"value": ...}`).
    pub fn information(skill: impl Into<String>, data: serde_json::Value) -> Self {
        let mut s = Self::base(skill, Status::Success);
        s.result = Some(ResultBody {
            kind: ResultKind::Information,
            summary: None,
            data: Some(ensure_object(data)),
            sources: None,
            file: None,
            files: None,
        });
        s
    }

    /// `status: success` with a single file.
    pub fn file(skill: impl Into<String>, file: FileRef) -> Self {
        let mut s = Self::base(skill, Status::Success);
        s.result = Some(ResultBody {
            kind: ResultKind::File,
            summary: None,
            data: None,
            sources: None,
            file: Some(file),
            files: None,
        });
        s
    }

    /// `status: failed` with a buyer-safe code/message.
    pub fn error(skill: impl Into<String>, code: ErrorCode, message: impl Into<String>, retryable: bool) -> Self {
        let mut s = Self::base(skill, Status::Failed);
        s.error = Some(ErrorBody { code, message: message.into(), retryable });
        s
    }

    /// `status: needs_input` (clarify-or-proceed; use sparingly per the spec).
    pub fn needs_input(skill: impl Into<String>, question: impl Into<String>, missing: Vec<String>) -> Self {
        let mut s = Self::base(skill, Status::NeedsInput);
        s.needs_input = Some(NeedsInput { question: question.into(), missing });
        s
    }

    /// Wrap a raw tool/skill payload into the canonical envelope: detect a file
    /// output, otherwise treat it as information (object-wrapped + sources lifted).
    /// This is THE single place that turns an upstream/tool payload into our shape,
    /// shared by every host so a provider swap never changes what a caller sees.
    pub fn wrap_tool_response(
        skill: impl Into<String>,
        payload: serde_json::Value,
        summary: Option<String>,
        meta: Meta,
    ) -> Self {
        let skill = skill.into();
        if let Some(file) = detect_file(&payload) {
            let mut s = Self::file(skill, file);
            if let Some(r) = s.result.as_mut() {
                r.summary = summary;
            }
            s.meta = meta;
            return s;
        }
        let (data, sources) = split_sources(payload);
        let mut s = Self::information(skill, data);
        if let Some(r) = s.result.as_mut() {
            r.sources = sources;
            r.summary = summary;
        }
        s.meta = meta;
        s
    }

    /// Builder: attach a one-line summary to an `ok` result.
    pub fn with_summary(mut self, summary: impl Into<String>) -> Self {
        if let Some(r) = self.result.as_mut() {
            r.summary = Some(summary.into());
        }
        self
    }

    /// Builder: attach billing/latency metadata.
    pub fn with_meta(mut self, meta: Meta) -> Self {
        self.meta = meta;
        self
    }

    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string(self)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn information_serializes_to_spec_shape() {
        let r = SkillResult::information("currency.convert", serde_json::json!({"eur": 0.92}))
            .with_summary("100 USD is about 92 EUR.");
        let v: serde_json::Value = serde_json::from_str(&r.to_json().unwrap()).unwrap();
        assert_eq!(v["faro_envelope"], "1");
        assert_eq!(v["skill"], "currency.convert");
        assert_eq!(v["status"], "success");
        assert_eq!(v["result"]["kind"], "information");
        assert_eq!(v["result"]["data"]["eur"], 0.92);
        // absent variants are omitted, not null
        assert!(v.get("error").is_none());
        assert!(v.get("needs_input").is_none());
    }

    #[test]
    fn error_is_buyer_safe_shape() {
        let r = SkillResult::error("image.create", ErrorCode::Timeout, "The upstream service timed out.", true);
        let v: serde_json::Value = serde_json::from_str(&r.to_json().unwrap()).unwrap();
        assert_eq!(v["status"], "failed");
        assert_eq!(v["error"]["code"], "timeout");
        assert_eq!(v["error"]["retryable"], true);
        assert!(v.get("result").is_none());
    }

    #[test]
    fn wrap_tool_response_detects_file_and_lifts_sources() {
        // A worker file payload becomes a file result.
        let f = SkillResult::wrap_tool_response(
            "image.create",
            serde_json::json!({"url": "https://files.askfaro.com/o/x.png", "mime": "image/png", "size_bytes": 5}),
            None,
            Meta::default(),
        );
        let v: serde_json::Value = serde_json::from_str(&f.to_json().unwrap()).unwrap();
        assert_eq!(v["result"]["kind"], "file");
        assert_eq!(v["result"]["file"]["filename"], "x.png");

        // An info payload with citations lifts them into `sources`.
        let i = SkillResult::wrap_tool_response(
            "research.answer",
            serde_json::json!({"answer": "Paris", "citations": ["https://a.com", {"url": "https://b.com", "title": "B"}]}),
            None,
            Meta::default(),
        );
        let v2: serde_json::Value = serde_json::from_str(&i.to_json().unwrap()).unwrap();
        assert_eq!(v2["result"]["kind"], "information");
        assert_eq!(v2["result"]["data"], serde_json::json!({"answer": "Paris"}));
        assert_eq!(v2["result"]["sources"][0]["url"], "https://a.com");
        assert_eq!(v2["result"]["sources"][1]["title"], "B");
    }

    #[test]
    fn information_data_is_always_an_object() {
        // A bare scalar is wrapped so `result.data` keeps a predictable shape.
        let r = SkillResult::information("calc.run", serde_json::json!(42));
        let v: serde_json::Value = serde_json::from_str(&r.to_json().unwrap()).unwrap();
        assert_eq!(v["result"]["data"]["value"], 42);
        // An object passes through unchanged.
        let r2 = SkillResult::information("x.y", serde_json::json!({"a": 1}));
        let v2: serde_json::Value = serde_json::from_str(&r2.to_json().unwrap()).unwrap();
        assert_eq!(v2["result"]["data"]["a"], 1);
    }

    #[test]
    fn file_result_carries_download_url() {
        let r = SkillResult::file(
            "image.create",
            FileRef {
                download_url: "https://files.askfaro.com/output/image/x.png".into(),
                mime: "image/png".into(),
                size_bytes: 42,
                filename: "x.png".into(),
                expires_at: None,
            },
        );
        let v: serde_json::Value = serde_json::from_str(&r.to_json().unwrap()).unwrap();
        assert_eq!(v["result"]["kind"], "file");
        assert_eq!(v["result"]["file"]["mime"], "image/png");
        assert!(v["result"]["file"].get("expires_at").is_none());
    }
}
