// @generated by scripts/vendor_free_tools.sh — DO NOT EDIT.
// Source of truth: faro-core/core-free/src/. Edit there and re-run the script;
// the core-sync CI job fails if this vendored copy drifts.

//! Core error type. Maps cleanly onto the envelope's `ErrorCode` so a failed
//! free-tool execution becomes a buyer-safe `SkillResult::error`.

use crate::free::envelope::ErrorCode;

#[derive(Debug, thiserror::Error)]
pub enum CoreError {
    #[error("unknown tool: {0}")]
    UnknownTool(String),

    #[error("invalid input: {0}")]
    InvalidInput(String),

    #[error("cloud transport not available: {0}")]
    Transport(String),

    #[error(transparent)]
    Json(#[from] serde_json::Error),
}

impl CoreError {
    /// The buyer-safe envelope code for this error.
    pub fn code(&self) -> ErrorCode {
        match self {
            CoreError::UnknownTool(_) => ErrorCode::NotFound,
            CoreError::InvalidInput(_) => ErrorCode::InvalidInput,
            CoreError::Transport(_) => ErrorCode::UpstreamFailed,
            CoreError::Json(_) => ErrorCode::Internal,
        }
    }

    /// Whether a bare retry could plausibly help.
    pub fn retryable(&self) -> bool {
        matches!(self, CoreError::Transport(_))
    }
}

pub type CoreResult<T> = Result<T, CoreError>;
