// @generated by scripts/vendor_free_tools.sh — DO NOT EDIT.
// Source of truth: faro-core/core-free/src/. Edit there and re-run the script;
// the core-sync CI job fails if this vendored copy drifts.

//! # faro-core-free
//!
//! The open-source (MIT) slice of the Faro core: the parts that run identically
//! on server and on-device with no network, no credentials, and no billing.
//!
//! - [`envelope`] — the normalized output envelope ([`envelope::SkillResult`]),
//!   the stable contract every skill returns (Spec 1).
//! - [`free_tools`] — deterministic, zero-cost tools that run in-process
//!   ([`free_tools::execute`]): calc, units, phone, astronomy, encoding,
//!   datetime, timezone, random.
//!
//! The selection gate, signed continuations, cloud client, charged-skill
//! execution, and billing live in the private `faro-core` crate and the cloud
//! services; none of that is here.

pub mod envelope;
pub mod error;
pub mod free_tools;

pub use envelope::SkillResult;
pub use error::{CoreError, CoreResult};

/// The crate version, surfaced to bindings for diagnostics.
pub fn version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

/// Execute a free tool by name with JSON-string params, returning the envelope as
/// a JSON string. This is the binding-friendly entry point: strings in, string
/// out, no Rust types cross the FFI boundary.
pub fn execute_free_tool_json(name: &str, params_json: &str) -> String {
    let params: serde_json::Value = match serde_json::from_str(params_json) {
        Ok(v) => v,
        Err(e) => {
            return SkillResult::error(
                format!("{name}.run"),
                envelope::ErrorCode::InvalidInput,
                format!("params is not valid JSON: {e}"),
                false,
            )
            .to_json()
            .unwrap_or_else(|_| "{}".to_string());
        }
    };
    free_tools::execute(name, params)
        .to_json()
        .unwrap_or_else(|_| "{}".to_string())
}

/// Wrap a raw tool/skill payload into the canonical envelope JSON. The single
/// builder both the server skill agent and faro-api call, so raw tools and skills
/// produce the identical shape. `payload_json` is the (security-normalized) tool
/// output; `meta_json` is the buyer-safe `Meta` ({credits_charged?, latency_ms?,
/// cached?, ...}); `summary` is an optional one-line recap.
pub fn wrap_tool_response_json(
    skill: &str,
    payload_json: &str,
    summary: Option<&str>,
    meta_json: &str,
    id: Option<&str>,
    idempotency_key: Option<&str>,
) -> String {
    let payload: serde_json::Value = serde_json::from_str(payload_json).unwrap_or(serde_json::Value::Null);
    let meta: envelope::Meta = serde_json::from_str(meta_json).unwrap_or_default();
    let mut sr = SkillResult::wrap_tool_response(skill, payload, summary.map(|s| s.to_string()), meta);
    sr.id = id.map(str::to_string);
    sr.idempotency_key = idempotency_key.map(str::to_string);
    sr.to_json().unwrap_or_else(|_| "{}".to_string())
}

/// Build a buyer-safe error envelope JSON. Shared so error shape never drifts.
pub fn build_error_json(
    skill: &str,
    code: &str,
    message: &str,
    retryable: bool,
    meta_json: &str,
    id: Option<&str>,
    idempotency_key: Option<&str>,
) -> String {
    let code = match code {
        "invalid_input" => envelope::ErrorCode::InvalidInput,
        "auth" => envelope::ErrorCode::Auth,
        "rate_limited" => envelope::ErrorCode::RateLimited,
        "insufficient_credits" => envelope::ErrorCode::InsufficientCredits,
        "not_found" => envelope::ErrorCode::NotFound,
        "timeout" => envelope::ErrorCode::Timeout,
        "upstream_failed" => envelope::ErrorCode::UpstreamFailed,
        _ => envelope::ErrorCode::Internal,
    };
    let meta: envelope::Meta = serde_json::from_str(meta_json).unwrap_or_default();
    let mut sr = SkillResult::error(skill, code, message, retryable).with_meta(meta);
    sr.id = id.map(str::to_string);
    sr.idempotency_key = idempotency_key.map(str::to_string);
    sr.to_json().unwrap_or_else(|_| "{}".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn execute_free_tool_json_roundtrips() {
        let out = execute_free_tool_json("units", r#"{"value": 100, "from_unit": "celsius", "to_unit": "fahrenheit"}"#);
        let v: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(v["status"], "success");
        assert_eq!(v["result"]["data"]["result"], 212);
    }

    #[test]
    fn execute_free_tool_json_handles_bad_json() {
        let out = execute_free_tool_json("calc", "not json");
        let v: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(v["status"], "failed");
        assert_eq!(v["error"]["code"], "invalid_input");
    }

    #[test]
    fn build_error_json_maps_insufficient_credits() {
        let out = build_error_json("image", "insufficient_credits", "Add credits to run this skill.", false, "{}", None, None);
        let v: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(v["status"], "failed");
        assert_eq!(v["error"]["code"], "insufficient_credits");
    }
}
