// @generated by scripts/vendor_free_tools.sh — DO NOT EDIT.
// Source of truth: faro-core/core-free/src/. Edit there and re-run the script;
// the core-sync CI job fails if this vendored copy drifts.

//! `astronomy`: solar and lunar times for a location and date, computed via
//! suncalc (port of the JavaScript suncalc library). A free tool — no network,
//! deterministic. Two operations:
//!   - `sun`   sunrise/sunset/dawn/dusk/solar_noon/day_length for lat/lon/date
//!   - `moon`  moon phase, illumination percentage, and trend for a date

use crate::free::error::CoreError;
use super::ToolOutput;
use suncalc::Timestamp;

pub(crate) fn run(params: serde_json::Value) -> ToolOutput {
    let op = params.get("operation").and_then(|v| v.as_str()).unwrap_or("sun");
    match op {
        "sun" => sun_op(&params),
        "moon" => moon_op(&params),
        other => Err(CoreError::InvalidInput(format!(
            "unknown operation `{other}` (sun, moon)"
        ))),
    }
}

// ---- shared helpers ---------------------------------------------------------

/// Parse "YYYY-MM-DD" (or today via jiff if absent) and return the Unix
/// millisecond timestamp for noon UTC on that date.
fn date_to_noon_ms(params: &serde_json::Value) -> Result<i64, CoreError> {
    let date_str = params.get("date").and_then(|v| v.as_str()).unwrap_or("").trim().to_string();
    let (y, m, d) = if date_str.is_empty() {
        // Use jiff to get today.
        let today = jiff::Zoned::now();
        let d = today.date();
        (d.year() as i32, d.month() as u32, d.day() as u32)
    } else {
        parse_ymd(&date_str)?
    };
    // seconds since epoch for noon UTC on the given date.
    let days_since_epoch = days_from_epoch(y, m, d);
    let noon_ms = (days_since_epoch as i64 * 86_400 + 12 * 3600) * 1000;
    Ok(noon_ms)
}

fn parse_ymd(s: &str) -> Result<(i32, u32, u32), CoreError> {
    let parts: Vec<&str> = s.splitn(3, '-').collect();
    if parts.len() != 3 {
        return Err(CoreError::InvalidInput("`date` must be YYYY-MM-DD".into()));
    }
    let y: i32 = parts[0].parse().map_err(|_| CoreError::InvalidInput("`date` must be YYYY-MM-DD".into()))?;
    let m: u32 = parts[1].parse().map_err(|_| CoreError::InvalidInput("`date` must be YYYY-MM-DD".into()))?;
    let d: u32 = parts[2].parse().map_err(|_| CoreError::InvalidInput("`date` must be YYYY-MM-DD".into()))?;
    if !(1..=12).contains(&m) || !(1..=31).contains(&d) {
        return Err(CoreError::InvalidInput("`date` month/day out of range".into()));
    }
    Ok((y, m, d))
}

/// Days since Unix epoch (1970-01-01) for a Gregorian date (proleptic).
fn days_from_epoch(y: i32, m: u32, d: u32) -> i64 {
    // Algorithm: convert to Julian Day Number, subtract epoch JDN.
    let y = y as i64;
    let m = m as i64;
    let d = d as i64;
    let jdn = (1461 * (y + 4800 + (m - 14) / 12)) / 4
        + (367 * (m - 2 - 12 * ((m - 14) / 12))) / 12
        - (3 * ((y + 4900 + (m - 14) / 12) / 100)) / 4
        + d - 32075;
    let epoch_jdn = 2440588_i64; // 1970-01-01
    jdn - epoch_jdn
}

fn ts_to_iso(ts: Timestamp, tz_offset_secs: i64) -> String {
    // Convert ms timestamp to an ISO-8601 local time string (offset tz).
    let secs = ts.0 / 1000 + tz_offset_secs;
    let (y, mo, d, h, mi, s) = epoch_secs_to_ymd_hms(secs);
    let off_abs = tz_offset_secs.abs();
    let off_sign = if tz_offset_secs >= 0 { '+' } else { '-' };
    format!("{y:04}-{mo:02}-{d:02}T{h:02}:{mi:02}:{s:02}{off_sign}{:02}:{:02}",
        off_abs / 3600, (off_abs % 3600) / 60)
}

fn epoch_secs_to_ymd_hms(secs: i64) -> (i64, i64, i64, i64, i64, i64) {
    let s = secs.rem_euclid(60);
    let total_min = secs.div_euclid(60);
    let mi = total_min.rem_euclid(60);
    let total_h = total_min.div_euclid(60);
    let h = total_h.rem_euclid(24);
    let days = total_h.div_euclid(24);
    // Civil date from days since epoch.
    let (y, mo, d) = days_to_ymd(days);
    (y, mo, d, h, mi, s)
}

fn days_to_ymd(days: i64) -> (i64, i64, i64) {
    let jdn = days + 2440588;
    let l = jdn + 68569;
    let n = (4 * l) / 146097;
    let l = l - (146097 * n + 3) / 4;
    let i = (4000 * (l + 1)) / 1461001;
    let l = l - (1461 * i) / 4 + 31;
    let j = (80 * l) / 2447;
    let d = l - (2447 * j) / 80;
    let l = j / 11;
    let m = j + 2 - 12 * l;
    let y = 100 * (n - 49) + i + l;
    (y, m, d)
}

fn coord(params: &serde_json::Value, key: &str, lo: f64, hi: f64) -> Result<f64, CoreError> {
    let v = params.get(key).and_then(|v| v.as_f64())
        .ok_or_else(|| CoreError::InvalidInput(format!("`{key}` is required (a number)")))?;
    if !((lo..=hi).contains(&v)) {
        return Err(CoreError::InvalidInput(format!("`{key}` must be between {lo} and {hi}")));
    }
    Ok(v)
}

// suncalc returns 0 ms timestamp (Timestamp(0)) when an event doesn't occur
// (polar day/night). We treat anything less than 1980 as absent.
fn ts_valid(ts: Timestamp) -> bool {
    ts.0 > 315_532_800_000 // 1980-01-01
}

// ---- sun --------------------------------------------------------------------

fn sun_op(params: &serde_json::Value) -> ToolOutput {
    let lat = coord(params, "latitude", -90.0, 90.0)?;
    let lon = coord(params, "longitude", -180.0, 180.0)?;
    let noon_ms = date_to_noon_ms(params)?;
    let tz_offset_secs = params.get("timezone_offset_seconds")
        .and_then(|v| v.as_i64())
        .unwrap_or(0);

    let times = suncalc::get_times(Timestamp(noon_ms), lat, lon, None);

    let fmt = |ts: Timestamp| -> serde_json::Value {
        if ts_valid(ts) {
            serde_json::json!(ts_to_iso(ts, tz_offset_secs))
        } else {
            serde_json::Value::Null
        }
    };

    let sunrise = fmt(times.sunrise);
    let sunset = fmt(times.sunset);
    let dawn = fmt(times.dawn);
    let dusk = fmt(times.dusk);
    let solar_noon = fmt(times.solar_noon);

    let day_length = if ts_valid(times.sunrise) && ts_valid(times.sunset) {
        let secs = (times.sunset.0 - times.sunrise.0) / 1000;
        serde_json::json!({
            "hours": (secs as f64 / 3600.0 * 10000.0).round() / 10000.0,
            "formatted": format!("{}h {}m", secs / 3600, (secs % 3600) / 60),
        })
    } else {
        serde_json::Value::Null
    };

    let polar = !ts_valid(times.sunrise) || !ts_valid(times.sunset);

    // Build a date string from noon_ms for the response.
    let (y, mo, d, _, _, _) = epoch_secs_to_ymd_hms(noon_ms / 1000);
    let date_str = format!("{y:04}-{mo:02}-{d:02}");

    let data = serde_json::json!({
        "latitude": lat,
        "longitude": lon,
        "date": date_str,
        "dawn": dawn,
        "sunrise": sunrise,
        "solar_noon": solar_noon,
        "sunset": sunset,
        "dusk": dusk,
        "day_length": day_length,
        "polar": polar,
    });
    let summary = if polar {
        format!("Polar condition on {date_str} at ({lat},{lon})")
    } else {
        format!("Sunrise: {sunrise}, Sunset: {sunset}")
    };
    Ok((data, summary))
}

// ---- moon -------------------------------------------------------------------

const PHASE_NAMES: &[&str] = &[
    "New Moon", "Waxing Crescent", "First Quarter", "Waxing Gibbous",
    "Full Moon", "Waning Gibbous", "Last Quarter", "Waning Crescent",
];

fn moon_op(params: &serde_json::Value) -> ToolOutput {
    let noon_ms = date_to_noon_ms(params)?;
    let illum = suncalc::moon_illumination(Timestamp(noon_ms));

    // phase: 0..1 (0=New, 0.5=Full, 1=New again)
    let phase = illum.phase;
    let index = ((phase * 8.0).floor() as usize).min(7);
    let illumination_percent = (illum.fraction * 100.0 * 10.0).round() / 10.0;
    let trend = if phase < 0.5 { "waxing" } else { "waning" };

    let (y, mo, d, _, _, _) = epoch_secs_to_ymd_hms(noon_ms / 1000);
    let date_str = format!("{y:04}-{mo:02}-{d:02}");

    let data = serde_json::json!({
        "date": date_str,
        "phase": (phase * 1000.0).round() / 1000.0,
        "phase_name": PHASE_NAMES[index],
        "illumination_percent": illumination_percent,
        "trend": trend,
    });
    let summary = format!("{}: {}% illuminated ({})", PHASE_NAMES[index], illumination_percent, trend);
    Ok((data, summary))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sun_known_date() {
        // New York City, 2024-06-21 (summer solstice, longest day)
        let (d, _) = sun_op(&serde_json::json!({
            "latitude": 40.7128,
            "longitude": -74.006,
            "date": "2024-06-21",
        })).unwrap();
        assert!(d["sunrise"].is_string(), "sunrise should be present");
        assert!(d["sunset"].is_string(), "sunset should be present");
        assert_eq!(d["polar"], false);
        let len = d["day_length"]["hours"].as_f64().unwrap();
        assert!(len > 14.0 && len < 16.0, "summer solstice day length ~15h, got {len}");
    }

    #[test]
    fn moon_full_moon() {
        // Known full moon: 2024-01-25
        let (d, _) = moon_op(&serde_json::json!({"date": "2024-01-25"})).unwrap();
        let illum = d["illumination_percent"].as_f64().unwrap();
        assert!(illum > 90.0, "should be near full, got {illum}%");
        assert!(d["phase_name"].as_str().unwrap().contains("Full") ||
                d["phase_name"].as_str().unwrap().contains("Gibbous"), "got {}", d["phase_name"]);
    }

    #[test]
    fn moon_new_moon() {
        // Known new moon: 2024-01-11
        let (d, _) = moon_op(&serde_json::json!({"date": "2024-01-11"})).unwrap();
        let illum = d["illumination_percent"].as_f64().unwrap();
        assert!(illum < 10.0, "should be near new moon, got {illum}%");
    }

    #[test]
    fn days_roundtrip() {
        // 1970-01-01 = day 0
        assert_eq!(days_from_epoch(1970, 1, 1), 0);
        // 2024-06-21
        let days = days_from_epoch(2024, 6, 21);
        let (y, m, d) = days_to_ymd(days);
        assert_eq!((y, m, d), (2024, 6, 21));
    }

    #[test]
    fn errors() {
        assert!(sun_op(&serde_json::json!({"latitude": 200.0, "longitude": 0.0})).is_err());
        assert!(moon_op(&serde_json::json!({"date": "not-a-date"})).is_err());
    }
}
