// @generated by scripts/vendor_free_tools.sh — DO NOT EDIT.
// Source of truth: faro-core/core-free/src/. Edit there and re-run the script;
// the core-sync CI job fails if this vendored copy drifts.

//! `calc`: exact calculator. A free tool — runs in-core, no LLM, no charge.
//! Three operations, dispatched on `operation` (default `evaluate`):
//!   - `evaluate`     scientific expression evaluation (fasteval, f64)
//!   - `base_convert` integer base conversion (2..=36)
//!   - `roman`        Roman-numeral <-> integer (1..=3999)

use crate::free::error::CoreError;
use super::ToolOutput;

pub(crate) fn run(params: serde_json::Value) -> ToolOutput {
    let op = params.get("operation").and_then(|v| v.as_str()).unwrap_or("evaluate");
    match op {
        "evaluate" => evaluate(&params),
        "base_convert" => base_convert(&params),
        "roman" => roman(&params),
        other => Err(CoreError::InvalidInput(format!(
            "unknown operation `{other}` (evaluate, base_convert, roman)"
        ))),
    }
}

// ---- evaluate ----------------------------------------------------------------

fn evaluate(params: &serde_json::Value) -> ToolOutput {
    let expr = params
        .get("expression")
        .and_then(|v| v.as_str())
        .ok_or_else(|| CoreError::InvalidInput("missing string field `expression`".into()))?;
    if expr.len() > 1000 {
        return Err(CoreError::InvalidInput("`expression` too long (max 1000 characters)".into()));
    }

    let value = eval_expr(expr)?;
    if !value.is_finite() {
        return Err(CoreError::InvalidInput(
            "result is undefined (e.g. division by zero or overflow)".into(),
        ));
    }

    let is_int = value.fract() == 0.0 && value.abs() < 9.007_199_254_740_992e15;
    let (result, result_string, result_type) = if is_int {
        let n = value as i64;
        (serde_json::json!(n), n.to_string(), "integer")
    } else {
        (serde_json::json!(value), value.to_string(), "number")
    };

    let data = serde_json::json!({
        "expression": expr,
        "result": result,
        "result_string": result_string,
        "result_type": result_type,
    });
    Ok((data, format!("{expr} = {result_string}")))
}

/// Evaluate a scientific expression to f64 via fasteval, with extra constants
/// and functions wired in via the namespace callback.
fn eval_expr(expr: &str) -> Result<f64, CoreError> {
    let mut cb = |name: &str, args: Vec<f64>| -> Option<f64> {
        match (name, args.as_slice()) {
            ("pi", []) => Some(std::f64::consts::PI),
            ("tau", []) => Some(std::f64::consts::TAU),
            ("sqrt", [x]) => Some(x.sqrt()),
            ("cbrt", [x]) => Some(x.cbrt()),
            ("exp", [x]) => Some(x.exp()),
            ("ln", [x]) => Some(x.ln()),
            ("log2", [x]) => Some(x.log2()),
            ("log10", [x]) => Some(x.log10()),
            ("degrees", [x]) => Some(x.to_degrees()),
            ("radians", [x]) => Some(x.to_radians()),
            ("hypot", [a, b]) => Some(a.hypot(*b)),
            ("gcd", [a, b]) => Some(gcd(*a, *b)),
            ("factorial", [x]) => factorial(*x),
            _ => None,
        }
    };
    fasteval::ez_eval(expr, &mut cb)
        .map_err(|e| CoreError::InvalidInput(format!("could not evaluate expression: {e}")))
}

fn gcd(a: f64, b: f64) -> f64 {
    let (mut a, mut b) = (a.abs().round() as u64, b.abs().round() as u64);
    while b != 0 {
        (a, b) = (b, a % b);
    }
    a as f64
}

fn factorial(x: f64) -> Option<f64> {
    if x.fract() != 0.0 || x < 0.0 || x > 170.0 {
        return None;
    }
    let n = x as u64;
    let mut acc = 1.0_f64;
    for k in 2..=n {
        acc *= k as f64;
    }
    Some(acc)
}

// ---- base_convert ------------------------------------------------------------

const DIGITS: &[u8] = b"0123456789abcdefghijklmnopqrstuvwxyz";

fn base_convert(params: &serde_json::Value) -> ToolOutput {
    let value = match params.get("value") {
        Some(serde_json::Value::String(s)) => s.trim().to_string(),
        Some(serde_json::Value::Number(n)) if n.is_i64() => n.to_string(),
        _ => return Err(CoreError::InvalidInput("`value` is required (a number, as a string)".into())),
    };
    if value.is_empty() {
        return Err(CoreError::InvalidInput("`value` is required (a number, as a string)".into()));
    }
    let from_base = base_arg(params, "from_base", Some(10))?;
    let to_base = base_arg(params, "to_base", None)?;

    let neg = value.starts_with('-');
    let digits = if neg { &value[1..] } else { value.as_str() };
    let mag = i128::from_str_radix(digits, from_base)
        .map_err(|_| CoreError::InvalidInput(format!("{value:?} is not a valid base-{from_base} number")))?;
    let n = if neg { -mag } else { mag };

    let result = int_to_base(n, to_base);
    let data = serde_json::json!({
        "input": value,
        "from_base": from_base,
        "to_base": to_base,
        "result": result,
        "decimal": n as i64,
    });
    Ok((data, format!("{value} (base {from_base}) = {result} (base {to_base})")))
}

fn base_arg(params: &serde_json::Value, key: &str, default: Option<u32>) -> Result<u32, CoreError> {
    let v = match params.get(key).and_then(|v| v.as_i64()) {
        Some(v) => v,
        None => match default {
            Some(d) => return Ok(d),
            None => return Err(CoreError::InvalidInput(format!("`{key}` is required"))),
        },
    };
    if !(2..=36).contains(&v) {
        return Err(CoreError::InvalidInput(format!("`{key}` must be between 2 and 36")));
    }
    Ok(v as u32)
}

fn int_to_base(n: i128, base: u32) -> String {
    if n == 0 {
        return "0".into();
    }
    let neg = n < 0;
    let mut n = n.unsigned_abs();
    let b = base as u128;
    let mut out = Vec::new();
    while n > 0 {
        out.push(DIGITS[(n % b) as usize]);
        n /= b;
    }
    if neg { out.push(b'-'); }
    out.reverse();
    String::from_utf8(out).unwrap()
}

// ---- roman -------------------------------------------------------------------

const ROMAN: &[(u32, &str)] = &[
    (1000, "M"), (900, "CM"), (500, "D"), (400, "CD"), (100, "C"), (90, "XC"),
    (50, "L"), (40, "XL"), (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I"),
];

fn roman(params: &serde_json::Value) -> ToolOutput {
    let action = params.get("action").and_then(|v| v.as_str()).unwrap_or("to_roman").to_lowercase();
    match action.as_str() {
        "to_roman" => {
            let n = params.get("value")
                .and_then(value_as_i64)
                .ok_or_else(|| CoreError::InvalidInput("`value` must be an integer 1-3999".into()))?;
            if !(1..=3999).contains(&n) {
                return Err(CoreError::InvalidInput("Roman numerals support integers 1-3999".into()));
            }
            let result = int_to_roman(n as u32);
            let data = serde_json::json!({"action": action, "input": n, "result": result});
            Ok((data, format!("{n} = {result}")))
        }
        "from_roman" => {
            let s = params.get("value")
                .and_then(|v| v.as_str())
                .map(|s| s.trim().to_uppercase())
                .filter(|s| !s.is_empty())
                .ok_or_else(|| CoreError::InvalidInput("`value` must be a Roman numeral string".into()))?;
            let total = roman_to_int(&s)?;
            if !(1..=3999).contains(&total) || int_to_roman(total) != s {
                return Err(CoreError::InvalidInput(format!("{s:?} is not a valid Roman numeral")));
            }
            let data = serde_json::json!({"action": action, "input": s, "result": total});
            Ok((data, format!("{s} = {total}")))
        }
        other => Err(CoreError::InvalidInput(format!(
            "`action` must be `to_roman` or `from_roman` (got {other:?})"
        ))),
    }
}

fn value_as_i64(v: &serde_json::Value) -> Option<i64> {
    v.as_i64().or_else(|| v.as_str().and_then(|s| s.trim().parse().ok()))
}

fn int_to_roman(mut n: u32) -> String {
    let mut out = String::new();
    for &(value, sym) in ROMAN {
        while n >= value {
            out.push_str(sym);
            n -= value;
        }
    }
    out
}

fn roman_to_int(s: &str) -> Result<u32, CoreError> {
    let val = |c: char| match c {
        'I' => Some(1_i64), 'V' => Some(5), 'X' => Some(10), 'L' => Some(50),
        'C' => Some(100), 'D' => Some(500), 'M' => Some(1000), _ => None,
    };
    let mut total = 0_i64;
    let mut prev = 0_i64;
    for c in s.chars().rev() {
        let v = val(c).ok_or_else(|| {
            CoreError::InvalidInput(format!("{s:?} contains invalid Roman-numeral characters"))
        })?;
        total += if v < prev { -v } else { v };
        prev = prev.max(v);
    }
    Ok(total.max(0) as u32)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn arithmetic_and_functions() {
        // fasteval exposes e() and pi() as zero-arg calls
        assert_eq!(eval_expr("2 + 2 * 3").unwrap(), 8.0);
        assert_eq!(eval_expr("(2 + 2) * 3").unwrap(), 12.0);
        assert_eq!(eval_expr("10 / 4").unwrap(), 2.5);
        assert_eq!(eval_expr("2 ^ 10").unwrap(), 1024.0);
        assert_eq!(eval_expr("17 % 5").unwrap(), 2.0);
        assert_eq!(eval_expr("sqrt(9)").unwrap(), 3.0);
        assert!((eval_expr("ln(e())").unwrap() - 1.0).abs() < 1e-12);
        assert!((eval_expr("sin(pi() / 2)").unwrap() - 1.0).abs() < 1e-12);
        assert_eq!(eval_expr("factorial(5)").unwrap(), 120.0);
        assert_eq!(eval_expr("gcd(12, 18)").unwrap(), 6.0);
    }

    #[test]
    fn evaluate_shape() {
        let (d, _) = evaluate(&serde_json::json!({"expression": "2 + 2"})).unwrap();
        assert_eq!(d["result"], 4);
        assert_eq!(d["result_type"], "integer");
        let (d, _) = evaluate(&serde_json::json!({"expression": "10 / 4"})).unwrap();
        assert_eq!(d["result"], 2.5);
        assert_eq!(d["result_type"], "number");
    }

    #[test]
    fn evaluate_errors() {
        assert!(evaluate(&serde_json::json!({"expression": "1 / 0"})).is_err());
        assert!(evaluate(&serde_json::json!({"expression": "1 +"})).is_err());
    }

    #[test]
    fn base_convert_roundtrips() {
        let (d, _) = base_convert(&serde_json::json!({"value": "255", "from_base": 10, "to_base": 16})).unwrap();
        assert_eq!(d["result"], "ff");
        let (d, _) = base_convert(&serde_json::json!({"value": "ff", "from_base": 16, "to_base": 2})).unwrap();
        assert_eq!(d["result"], "11111111");
        let (d, _) = base_convert(&serde_json::json!({"value": "-10", "from_base": 10, "to_base": 2})).unwrap();
        assert_eq!(d["result"], "-1010");
        assert!(base_convert(&serde_json::json!({"value": "9", "from_base": 8, "to_base": 10})).is_err());
    }

    #[test]
    fn roman_both_directions() {
        let (d, _) = roman(&serde_json::json!({"action": "to_roman", "value": 2024})).unwrap();
        assert_eq!(d["result"], "MMXXIV");
        let (d, _) = roman(&serde_json::json!({"action": "from_roman", "value": "MMXXIV"})).unwrap();
        assert_eq!(d["result"], 2024);
        assert!(roman(&serde_json::json!({"action": "from_roman", "value": "IIII"})).is_err());
        assert!(roman(&serde_json::json!({"action": "to_roman", "value": 5000})).is_err());
    }
}
