// @generated by scripts/vendor_free_tools.sh — DO NOT EDIT.
// Source of truth: faro-core/core-free/src/. Edit there and re-run the script;
// the core-sync CI job fails if this vendored copy drifts.

//! `datetime`: duration between dates, interval arithmetic, calendar facts, and
//! business-day counts. Free/local, dispatches on `operation`. Single source of
//! truth for the server `datetime` namespace too (the Python
//! `internal_tools/datetime_tools.py` it replaces). Calendar math runs on `jiff`;
//! country/subdivision holiday calendars come from the `holidays` crate (mirrors
//! the Python `holidays` package). Times without an offset are treated as naive
//! UTC, like the server; zone-aware work lives in `timezone`.

use jiff::civil::{Date, DateTime};
use jiff::{Span, Timestamp, Unit};

use super::ToolOutput;
use crate::free::error::CoreError;

const MAX_SPAN_DAYS: i32 = 366 * 20; // cap business-day iteration so a call can't fan out forever

fn invalid(msg: impl Into<String>) -> CoreError {
    CoreError::InvalidInput(msg.into())
}

/// `jiff` returns the system clock; under test the mod-level `now_ms` is frozen,
/// but these tools always pass explicit dates in tests, so `today` is never hit.
fn today_midnight() -> DateTime {
    Timestamp::now().to_zoned(jiff::tz::TimeZone::UTC).datetime().date().at(0, 0, 0, 0)
}

/// Parse `YYYY-MM-DD` or ISO 8601. An explicit offset (or `Z`) fixes the instant
/// and is normalized to naive UTC, matching the server's `dateutil.isoparse` +
/// `astimezone(utc).replace(tzinfo=None)`.
fn parse_dt(v: Option<&str>, field: &str, default: Option<DateTime>) -> Result<DateTime, CoreError> {
    let s = match v.map(str::trim).filter(|x| !x.is_empty()) {
        Some(s) => s,
        None => return default.ok_or_else(|| invalid(format!("`{field}` is required (YYYY-MM-DD or ISO 8601)"))),
    };
    if let Ok(ts) = s.parse::<Timestamp>() {
        return Ok(ts.to_zoned(jiff::tz::TimeZone::UTC).datetime());
    }
    let norm = s.replacen(' ', "T", 1); // dateutil accepts a space separator
    if let Ok(dt) = norm.parse::<DateTime>() {
        return Ok(dt);
    }
    if let Ok(d) = s.parse::<Date>() {
        return Ok(d.at(0, 0, 0, 0));
    }
    Err(invalid(format!("`{field}` must be YYYY-MM-DD or ISO 8601")))
}

fn iget(p: &serde_json::Value, k: &str) -> i64 {
    p.get(k).and_then(|v| v.as_i64()).unwrap_or(0)
}

fn iso(dt: DateTime) -> String {
    dt.strftime("%Y-%m-%dT%H:%M:%S").to_string()
}

fn weekday_name(dt: DateTime) -> String {
    dt.strftime("%A").to_string()
}

pub(crate) fn run(params: serde_json::Value) -> ToolOutput {
    match params.get("operation").and_then(|v| v.as_str()).unwrap_or("") {
        "diff" => diff(&params),
        "add" => add(&params),
        "weekday" => weekday(&params),
        "business_days" => business_days(&params),
        "" => Err(invalid("missing `operation` (diff, add, weekday, business_days)")),
        other => Err(invalid(format!("unknown operation `{other}`"))),
    }
}

fn diff(p: &serde_json::Value) -> ToolOutput {
    let start = parse_dt(p.get("start").and_then(|v| v.as_str()), "start", None)?;
    let end = parse_dt(p.get("end").and_then(|v| v.as_str()), "end", Some(today_midnight()))?;
    let secs = start.until((Unit::Second, end)).map_err(|e| invalid(e.to_string()))?.get_seconds();
    let direction = if secs > 0 { "future" } else if secs < 0 { "past" } else { "same" };
    let (lo, hi) = if start <= end { (start, end) } else { (end, start) };
    let cal = calendar_breakdown(lo, hi)?;
    let a = secs.unsigned_abs() as f64;
    let data = serde_json::json!({
        "start": iso(start),
        "end": iso(end),
        "direction": direction,
        "total": {
            "seconds": secs.abs(),
            "minutes": (a / 60.0 * 1e6).round() / 1e6,
            "hours": (a / 3600.0 * 1e6).round() / 1e6,
            "days": (a / 86400.0 * 1e6).round() / 1e6,
            "weeks": (a / 604800.0 * 1e6).round() / 1e6,
        },
        "calendar": cal,
    });
    Ok((data, format!("{} {direction}", fmt_cal(&cal))))
}

fn fmt_cal(c: &serde_json::Value) -> String {
    format!("{}y {}m {}d", c["years"], c["months"], c["days"])
}

/// relativedelta-style absolute breakdown between `lo` <= `hi`. `jiff` balances a
/// year-largest span into years/months/weeks/days/...; we fold weeks into days so
/// the shape matches Python's `relativedelta` (which reports no weeks component).
fn calendar_breakdown(lo: DateTime, hi: DateTime) -> Result<serde_json::Value, CoreError> {
    let span = lo.until((Unit::Year, hi)).map_err(|e| invalid(e.to_string()))?;
    Ok(serde_json::json!({
        "years": span.get_years(),
        "months": span.get_months(),
        "days": span.get_days() + span.get_weeks() * 7,
        "hours": span.get_hours(),
        "minutes": span.get_minutes(),
        "seconds": span.get_seconds(),
    }))
}

fn add(p: &serde_json::Value) -> ToolOutput {
    let base = parse_dt(p.get("date").and_then(|v| v.as_str()), "date", Some(today_midnight()))?;
    let span = Span::new()
        .try_years(iget(p, "years")).and_then(|s| s.try_months(iget(p, "months")))
        .and_then(|s| s.try_weeks(iget(p, "weeks"))).and_then(|s| s.try_days(iget(p, "days")))
        .and_then(|s| s.try_hours(iget(p, "hours"))).and_then(|s| s.try_minutes(iget(p, "minutes")))
        .and_then(|s| s.try_seconds(iget(p, "seconds")))
        .map_err(|_| invalid("date arithmetic out of range"))?;
    let r = base.checked_add(span).map_err(|_| invalid("date arithmetic overflowed"))?;
    let data = serde_json::json!({
        "base": iso(base),
        "result": iso(r),
        "date": r.date().strftime("%Y-%m-%d").to_string(),
        "day_of_week": weekday_name(r),
    });
    Ok((data, format!("-> {}", iso(r))))
}

fn weekday(p: &serde_json::Value) -> ToolOutput {
    let d = parse_dt(p.get("date").and_then(|v| v.as_str()), "date", Some(today_midnight()))?;
    let num = d.weekday().to_monday_one_offset(); // Mon=1 .. Sun=7
    let iso_wd = d.date().iso_week_date();
    let data = serde_json::json!({
        "date": d.date().strftime("%Y-%m-%d").to_string(),
        "day_of_week": weekday_name(d),
        "weekday_number": num,
        "is_weekend": num >= 6,
        "iso_week": iso_wd.week(),
        "iso_week_year": iso_wd.year(),
        "day_of_year": d.date().day_of_year(),
        "quarter": (d.month() - 1) / 3 + 1,
    });
    Ok((data, format!("{} is a {}", d.date(), weekday_name(d))))
}

fn business_days(p: &serde_json::Value) -> ToolOutput {
    let mut s = parse_dt(p.get("start").and_then(|v| v.as_str()), "start", None)?.date();
    let mut e = parse_dt(p.get("end").and_then(|v| v.as_str()), "end", Some(today_midnight()))?.date();
    if e < s {
        std::mem::swap(&mut s, &mut e);
    }
    if s.until((Unit::Day, e)).map_err(|e| invalid(e.to_string()))?.get_days() > MAX_SPAN_DAYS {
        return Err(invalid("date range too large (max ~20 years)"));
    }

    // National holiday calendar, mirroring the server `holidays` namespace. The
    // `holidays` crate tracks national days only (no subdivision support yet), so
    // a subdivision request is rejected rather than silently widened to national.
    let country = p.get("country").and_then(|v| v.as_str()).filter(|c| !c.is_empty());
    if p.get("subdivision").and_then(|v| v.as_str()).is_some_and(|c| !c.is_empty()) {
        return Err(invalid("subdivision holiday calendars are not available on the local datetime tool; use country only"));
    }
    let country_enum = match country {
        Some(c) => Some(parse_country(c)?),
        None => None,
    };

    let (mut total, mut biz, mut weekend, mut holiday) = (0u32, 0u32, 0u32, 0u32);
    let mut cur = s;
    while cur <= e {
        total += 1;
        if cur.weekday().to_monday_one_offset() >= 6 {
            weekend += 1;
        } else if country_enum.is_some_and(|c| is_holiday(c, cur)) {
            holiday += 1;
        } else {
            biz += 1;
        }
        cur = cur.tomorrow().map_err(|e| invalid(e.to_string()))?;
    }

    let data = serde_json::json!({
        "start": s.strftime("%Y-%m-%d").to_string(),
        "end": e.strftime("%Y-%m-%d").to_string(),
        "inclusive": true,
        "total_days": total,
        "business_days": biz,
        "weekend_days": weekend,
        "holiday_days": holiday,
        "country": country.map(|c| c.to_uppercase()),
    });
    Ok((data, format!("{biz} business day(s)")))
}

fn parse_country(c: &str) -> Result<holidays::Country, CoreError> {
    static INIT: std::sync::Once = std::sync::Once::new();
    INIT.call_once(|| { let _ = holidays::init(); }); // load the holiday database once per process
    c.to_uppercase().parse::<holidays::Country>().map_err(|_| {
        invalid(format!(
            "unsupported country '{c}'; use the holidays `countries` tool for supported codes"
        ))
    })
}

fn is_holiday(country: holidays::Country, d: Date) -> bool {
    match chrono::NaiveDate::from_ymd_opt(d.year() as i32, d.month() as u32, d.day() as u32) {
        Some(nd) => holidays::contains(country, nd).unwrap_or(false),
        None => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    fn d(v: serde_json::Value) -> serde_json::Value {
        run(v).unwrap().0
    }

    #[test]
    fn diff_calendar() {
        let r = d(serde_json::json!({"operation":"diff","start":"2020-01-15","end":"2023-03-20"}));
        assert_eq!(r["start"], "2020-01-15T00:00:00");
        assert_eq!(r["calendar"], serde_json::json!({"years":3,"months":2,"days":5,"hours":0,"minutes":0,"seconds":0}));
        assert_eq!(r["direction"], "future");
        assert_eq!(r["total"]["seconds"], 100224000);
        assert_eq!(r["total"]["weeks"], 165.714286);
    }
    #[test]
    fn diff_folds_weeks_into_days() {
        let r = d(serde_json::json!({"operation":"diff","start":"2024-02-25T07:00:00","end":"2024-05-03T23:30:00"}));
        assert_eq!(r["calendar"], serde_json::json!({"years":0,"months":2,"days":8,"hours":16,"minutes":30,"seconds":0}));
    }
    #[test]
    fn diff_offset_normalized_to_utc() {
        let r = d(serde_json::json!({"operation":"diff","start":"2026-06-06T14:30:00+05:00","end":"2026-06-06T14:30:00Z"}));
        assert_eq!(r["start"], "2026-06-06T09:30:00");
        assert_eq!(r["end"], "2026-06-06T14:30:00");
        assert_eq!(r["calendar"]["hours"], 5);
    }
    #[test]
    fn diff_past_direction() {
        let r = d(serde_json::json!({"operation":"diff","start":"2026-06-20","end":"2026-06-01"}));
        assert_eq!(r["direction"], "past");
        assert_eq!(r["calendar"]["days"], 19);
    }
    #[test]
    fn add_clamps_month_end() {
        let r = d(serde_json::json!({"operation":"add","date":"2026-01-31","months":1}));
        assert_eq!(r["result"], "2026-02-28T00:00:00");
        assert_eq!(r["date"], "2026-02-28");
        assert_eq!(r["day_of_week"], "Saturday");
    }
    #[test]
    fn add_combined_units() {
        let r = d(serde_json::json!({"operation":"add","date":"2026-06-06T14:30:00","years":1,"months":2,"weeks":1,"days":3,"hours":5,"minutes":10,"seconds":20}));
        assert_eq!(r["result"], "2027-08-16T19:40:20");
        assert_eq!(r["day_of_week"], "Monday");
    }
    #[test]
    fn add_negative() {
        let r = d(serde_json::json!({"operation":"add","date":"2026-03-15","days":-20}));
        assert_eq!(r["result"], "2026-02-23T00:00:00");
    }
    #[test]
    fn weekday_facts() {
        let r = d(serde_json::json!({"operation":"weekday","date":"2026-06-14"}));
        assert_eq!(r["day_of_week"], "Sunday");
        assert_eq!(r["weekday_number"], 7);
        assert_eq!(r["is_weekend"], true);
        assert_eq!(r["iso_week"], 24);
        assert_eq!(r["iso_week_year"], 2026);
        assert_eq!(r["day_of_year"], 165);
        assert_eq!(r["quarter"], 2);
    }
    #[test]
    fn weekday_iso_year_rollover() {
        let r = d(serde_json::json!({"operation":"weekday","date":"2024-12-31"}));
        assert_eq!(r["iso_week"], 1);
        assert_eq!(r["iso_week_year"], 2025);
        assert_eq!(r["day_of_year"], 366);
    }
    #[test]
    fn business_days_plain() {
        let r = d(serde_json::json!({"operation":"business_days","start":"2026-06-15","end":"2026-06-19"}));
        assert_eq!(r, serde_json::json!({"start":"2026-06-15","end":"2026-06-19","inclusive":true,"total_days":5,"business_days":5,"weekend_days":0,"holiday_days":0,"country":null}));
    }
    #[test]
    fn business_days_us_july4() {
        let r = d(serde_json::json!({"operation":"business_days","start":"2026-07-01","end":"2026-07-07","country":"US"}));
        assert_eq!(r["total_days"], 7);
        assert_eq!(r["weekend_days"], 2);
        assert_eq!(r["holiday_days"], 1); // observed Jul 3 (Jul 4 falls on Saturday)
        assert_eq!(r["business_days"], 4);
        assert_eq!(r["country"], "US");
    }
    #[test]
    fn business_days_us_year_boundary() {
        let r = d(serde_json::json!({"operation":"business_days","start":"2026-12-20","end":"2027-01-05","country":"US"}));
        assert_eq!(r["total_days"], 17);
        assert_eq!(r["weekend_days"], 5);
        assert_eq!(r["holiday_days"], 2); // Christmas + New Year's Day
        assert_eq!(r["business_days"], 10);
    }
    #[test]
    fn business_days_gb_no_holiday_that_week() {
        let r = d(serde_json::json!({"operation":"business_days","start":"2026-07-01","end":"2026-07-07","country":"GB"}));
        assert_eq!(r["holiday_days"], 0);
        assert_eq!(r["business_days"], 5);
    }
}
