// @generated by scripts/vendor_free_tools.sh — DO NOT EDIT.
// Source of truth: faro-core/core-free/src/. Edit there and re-run the script;
// the core-sync CI job fails if this vendored copy drifts.

//! `encoding`: hashing, base64 / URL transforms, UUID generation, and JWT decode.
//! A free tool — deterministic, in-core, runs anywhere. Dispatches on `operation`
//! (the namespace bundles several sub-tools behind one local skill). Mirrors the
//! server `internal_tools/encoding.py` contract so the local and cloud paths agree.

use base64::Engine;
use md5::Md5;
use sha1::Sha1;
use sha2::{Digest, Sha256, Sha512};

use super::ToolOutput;
use crate::free::error::CoreError;

fn s<'a>(params: &'a serde_json::Value, key: &str) -> Option<&'a str> {
    params.get(key).and_then(|v| v.as_str())
}

pub(crate) fn run(params: serde_json::Value) -> ToolOutput {
    let op = s(&params, "operation")
        .or_else(|| s(&params, "action").filter(|_| params.get("token").is_some()))
        .ok_or_else(|| CoreError::InvalidInput(
            "missing `operation` (one of: hash, base64, url, uuid, jwt_decode)".into(),
        ))?
        .to_lowercase();
    match op.as_str() {
        "hash" => hash(&params),
        "base64" => base64_op(&params),
        "url" => url_op(&params),
        "uuid" => uuid_op(&params),
        "jwt_decode" | "jwt" => jwt_decode(&params),
        other => Err(CoreError::InvalidInput(format!("unknown operation `{other}`"))),
    }
}

fn need_text(params: &serde_json::Value) -> Result<String, CoreError> {
    s(params, "text").map(|t| t.to_string()).ok_or_else(|| CoreError::InvalidInput("`text` is required (string)".into()))
}

fn hash(params: &serde_json::Value) -> ToolOutput {
    let text = need_text(params)?;
    let algo = s(params, "algorithm").unwrap_or("sha256").to_lowercase();
    let digest: Vec<u8> = match algo.as_str() {
        "md5" => Md5::digest(text.as_bytes()).to_vec(),
        "sha1" => Sha1::digest(text.as_bytes()).to_vec(),
        "sha256" => Sha256::digest(text.as_bytes()).to_vec(),
        "sha512" => Sha512::digest(text.as_bytes()).to_vec(),
        _ => return Err(CoreError::InvalidInput("`algorithm` must be one of md5, sha1, sha256, sha512".into())),
    };
    let data = serde_json::json!({
        "algorithm": algo,
        "hex": hex::encode(&digest),
        "base64": base64::engine::general_purpose::STANDARD.encode(&digest),
    });
    Ok((data, format!("{algo} digest computed")))
}

fn base64_op(params: &serde_json::Value) -> ToolOutput {
    let text = need_text(params)?;
    let action = s(params, "action").unwrap_or("encode").to_lowercase();
    let url_safe = params.get("url_safe").and_then(|v| v.as_bool()).unwrap_or(false);
    let std_e = &base64::engine::general_purpose::STANDARD;
    let url_e = &base64::engine::general_purpose::URL_SAFE;
    let out = match action.as_str() {
        "encode" => if url_safe { url_e.encode(text.as_bytes()) } else { std_e.encode(text.as_bytes()) },
        "decode" => {
            let padded = {
                let t = text.trim();
                let pad = (4 - t.len() % 4) % 4;
                format!("{t}{}", "=".repeat(pad))
            };
            let bytes = if url_safe { url_e.decode(padded.as_bytes()) } else { std_e.decode(padded.as_bytes()) }
                .map_err(|_| CoreError::InvalidInput("input is not valid base64".into()))?;
            String::from_utf8(bytes).map_err(|_| CoreError::InvalidInput("decoded bytes are not UTF-8 text".into()))?
        }
        _ => return Err(CoreError::InvalidInput("`action` must be 'encode' or 'decode'".into())),
    };
    Ok((serde_json::json!({"action": action, "result": out}), "base64 transform".into()))
}

// Python `urllib.parse.quote` never quotes letters, digits, or the unreserved
// `_.-~`, and keeps `/` (its default `safe`) unquoted too. `quote_plus` uses the
// same unreserved set but DOES quote `/` and renders spaces as `+`. The
// percent-encoding crate encodes the complement of an AsciiSet, so we start from
// NON_ALPHANUMERIC (encode everything) and clear the chars Python leaves alone.
const QUOTE: &percent_encoding::AsciiSet = &percent_encoding::NON_ALPHANUMERIC
    .remove(b'_').remove(b'.').remove(b'-').remove(b'~').remove(b'/');
const QUOTE_PLUS: &percent_encoding::AsciiSet = &percent_encoding::NON_ALPHANUMERIC
    .remove(b'_').remove(b'.').remove(b'-').remove(b'~');

fn url_op(params: &serde_json::Value) -> ToolOutput {
    use percent_encoding::{percent_decode_str, utf8_percent_encode};
    let text = need_text(params)?;
    let action = s(params, "action").unwrap_or("encode").to_lowercase();
    let plus = params.get("plus").and_then(|v| v.as_bool()).unwrap_or(false);
    let out = match action.as_str() {
        "encode" => {
            // space is the only char that maps to %20, so a post-pass to '+' is exact.
            if plus { utf8_percent_encode(&text, QUOTE_PLUS).to_string().replace("%20", "+") }
            else { utf8_percent_encode(&text, QUOTE).to_string() }
        }
        "decode" => {
            let prepped = if plus { text.replace('+', " ") } else { text.clone() };
            percent_decode_str(&prepped).decode_utf8()
                .map_err(|_| CoreError::InvalidInput("input is not valid percent-encoding".into()))?
                .to_string()
        }
        _ => return Err(CoreError::InvalidInput("`action` must be 'encode' or 'decode'".into())),
    };
    Ok((serde_json::json!({"action": action, "result": out}), "url transform".into()))
}

fn rand_bytes(n: usize) -> Result<Vec<u8>, CoreError> {
    let mut b = vec![0u8; n];
    getrandom::getrandom(&mut b).map_err(|_| CoreError::InvalidInput("randomness unavailable".into()))?;
    Ok(b)
}

fn fmt_uuid(b: &[u8; 16]) -> String {
    let h = hex::encode(b);
    format!("{}-{}-{}-{}-{}", &h[0..8], &h[8..12], &h[12..16], &h[16..20], &h[20..32])
}

fn uuid_op(params: &serde_json::Value) -> ToolOutput {
    let version = params.get("version").and_then(|v| v.as_i64()).unwrap_or(4);
    let count = params.get("count").and_then(|v| v.as_i64()).unwrap_or(1).clamp(1, 100) as usize;
    let mut ids = Vec::with_capacity(count);
    for _ in 0..count {
        let mut b: [u8; 16] = rand_bytes(16)?.try_into().unwrap();
        match version {
            4 => { b[6] = (b[6] & 0x0F) | 0x40; b[8] = (b[8] & 0x3F) | 0x80; }
            7 => {
                let ms = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH)
                    .map(|d| d.as_millis() as u64).unwrap_or(0) & ((1u64 << 48) - 1);
                let ts = ms.to_be_bytes();
                b[0..6].copy_from_slice(&ts[2..8]);
                b[6] = (b[6] & 0x0F) | 0x70; b[8] = (b[8] & 0x3F) | 0x80;
            }
            _ => return Err(CoreError::InvalidInput("`version` must be 4 or 7".into())),
        }
        ids.push(fmt_uuid(&b));
    }
    Ok((serde_json::json!({"version": version, "count": ids.len(), "uuids": ids}), format!("{count} uuid(s)")))
}

fn jwt_decode(params: &serde_json::Value) -> ToolOutput {
    let token = s(params, "token").map(|t| t.trim().to_string())
        .filter(|t| !t.is_empty())
        .ok_or_else(|| CoreError::InvalidInput("`token` is required (a JWT string)".into()))?;
    let parts: Vec<&str> = token.split('.').collect();
    if parts.len() < 2 {
        return Err(CoreError::InvalidInput("not a decodable JWT".into()));
    }
    let seg = |p: &str| -> Result<serde_json::Value, CoreError> {
        let pad = (4 - p.len() % 4) % 4;
        let padded = format!("{p}{}", "=".repeat(pad));
        let bytes = base64::engine::general_purpose::URL_SAFE.decode(padded.as_bytes())
            .map_err(|_| CoreError::InvalidInput("not a decodable JWT".into()))?;
        serde_json::from_slice(&bytes).map_err(|_| CoreError::InvalidInput("not a decodable JWT".into()))
    };
    let header = seg(parts[0])?;
    let claims = seg(parts[1])?;
    let data = serde_json::json!({
        "header": header,
        "payload": claims,
        "signature_present": parts.len() == 3 && !parts[2].is_empty(),
        "verified": false,
    });
    Ok((data, "JWT decoded (signature not verified)".into()))
}

#[cfg(test)]
mod tests {
    use super::*;
    fn run_op(v: serde_json::Value) -> serde_json::Value { run(v).unwrap().0 }

    #[test]
    fn hash_sha256() {
        let d = run_op(serde_json::json!({"operation":"hash","text":"abc"}));
        assert_eq!(d["hex"], "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");
    }
    #[test]
    fn base64_roundtrip() {
        let e = run_op(serde_json::json!({"operation":"base64","text":"hello"}));
        assert_eq!(e["result"], "aGVsbG8=");
        let d = run_op(serde_json::json!({"operation":"base64","action":"decode","text":"aGVsbG8="}));
        assert_eq!(d["result"], "hello");
    }
    #[test]
    fn url_encode() {
        // Matches Python quote("a b/c") == "a%20b/c" ('/' is safe by default).
        let e = run_op(serde_json::json!({"operation":"url","text":"a b/c"}));
        assert_eq!(e["result"], "a%20b/c");
    }
    #[test]
    fn url_encode_plus() {
        // Matches Python quote_plus("a b/c") == "a+b%2Fc" (space->+, '/' quoted).
        let e = run_op(serde_json::json!({"operation":"url","text":"a b/c","plus":true}));
        assert_eq!(e["result"], "a+b%2Fc");
    }
    #[test]
    fn url_roundtrip_unreserved() {
        // Unreserved set is left intact, like Python.
        let e = run_op(serde_json::json!({"operation":"url","text":"A-Za-z0-9_.~"}));
        assert_eq!(e["result"], "A-Za-z0-9_.~");
    }
    #[test]
    fn uuid_v4_shape() {
        let d = run_op(serde_json::json!({"operation":"uuid","count":2}));
        assert_eq!(d["count"], 2);
        assert_eq!(d["uuids"].as_array().unwrap().len(), 2);
        assert_eq!(d["uuids"][0].as_str().unwrap().len(), 36);
    }
    #[test]
    fn jwt_decodes_payload() {
        // {"alg":"HS256"} . {"sub":"42"} . sig
        let t = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0MiJ9.x";
        let d = run_op(serde_json::json!({"operation":"jwt_decode","token":t}));
        assert_eq!(d["payload"]["sub"], "42");
        assert_eq!(d["verified"], false);
        assert_eq!(d["signature_present"], true);
    }
}
