// @generated by scripts/vendor_free_tools.sh — DO NOT EDIT.
// Source of truth: faro-core/core-free/src/. Edit there and re-run the script;
// the core-sync CI job fails if this vendored copy drifts.

//! Free / local tools: deterministic, zero-cost capabilities that run in-process
//! and identically on server and device (SKILL_LAYER_STRATEGY.md §3.2/§8). These
//! are "mostly code, not LLM instructions," so they ship open and local. Step 0
//! seeds two (calc, units) to prove the path end-to-end; the local-pack wave ports
//! the rest of the free computational catalog here.
//!
//! Every tool returns the normalized envelope (Spec 1), so a free tool and a
//! charged skill are indistinguishable to the calling model.

mod astronomy;
mod calc;
mod datetime;
mod encoding;
mod phone;
mod random;
mod timer;
mod timezone;
mod units;

use crate::free::envelope::{Meta, SkillResult};
use crate::free::error::CoreError;

/// Names of the free tools available in this build.
pub fn available() -> Vec<&'static str> {
    vec!["astronomy", "calc", "datetime", "encoding", "phone", "random", "timer", "timezone", "units"]
}

/// Execute a free tool by name with JSON `params`, returning a `SkillResult`
/// envelope. Errors are mapped to buyer-safe envelope errors, never panics.
pub fn execute(name: &str, params: serde_json::Value) -> SkillResult {
    // `name` is either a base tool name (`calc`) or a full raw-tool id
    // (`calc.base_convert`). A full id resolves to the base executor with its
    // `operation` param injected — byte-identical to the server, which does
    // `namespace, _, operation = handler.partition("."); {**args, "operation": operation}`
    // (faro-api services/internal_tools/__init__.py::_run_via_core). A bare base
    // name passes through untouched, so the operation comes from the params (or the
    // tool's own default) exactly as before.
    let (base, params) = resolve_id(name, params);
    let skill = format!("{base}.run");
    let started = now_ms();
    let outcome = match base {
        "astronomy" => astronomy::run(params),
        "calc" => calc::run(params),
        "datetime" => datetime::run(params),
        "encoding" => encoding::run(params),
        "phone" => phone::run(params),
        "random" => random::run(params),
        "timer" => timer::run(params),
        "timezone" => timezone::run(params),
        "units" => units::run(params),
        other => Err(CoreError::UnknownTool(other.to_string())),
    };
    let latency = now_ms().saturating_sub(started);
    match outcome {
        Ok((data, summary)) => SkillResult::information(&skill, data)
            .with_summary(summary)
            .with_meta(Meta { credits_charged: Some(0.0), latency_ms: Some(latency), ..Default::default() }),
        Err(e) => SkillResult::error(&skill, e.code(), e.to_string(), e.retryable())
            .with_meta(Meta { credits_charged: Some(0.0), latency_ms: Some(latency), ..Default::default() }),
    }
}

/// Split a raw-tool id into `(base, params)`, injecting the addressed operation.
///
/// A `name` containing a `.` is `<namespace>.<operation>` (split on the FIRST dot,
/// like the server's `str.partition`): the operation is written into the params,
/// overriding any `operation` already there, so the id always wins — matching the
/// server's `{**args, "operation": operation}`. A bare name is returned unchanged.
fn resolve_id(name: &str, params: serde_json::Value) -> (&str, serde_json::Value) {
    match name.split_once('.') {
        Some((base, operation)) => {
            let mut params = params;
            match params.as_object_mut() {
                Some(map) => {
                    map.insert("operation".to_string(), serde_json::Value::String(operation.to_string()));
                }
                // The tools expect an object; if a caller passes something else,
                // build the minimal object the dispatch needs (the server always
                // sends a dict, so this only guards odd on-device inputs).
                None => params = serde_json::json!({ "operation": operation }),
            }
            (base, params)
        }
        None => (name, params),
    }
}

/// Each free tool returns its information `data` plus a one-line `summary`.
pub(crate) type ToolOutput = Result<(serde_json::Value, String), CoreError>;

#[cfg(not(test))]
fn now_ms() -> u64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_millis() as u64).unwrap_or(0)
}

// Deterministic clock under test so latency_ms assertions don't flake.
#[cfg(test)]
fn now_ms() -> u64 {
    0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unknown_tool_is_not_found_error() {
        let r = execute("nope", serde_json::json!({}));
        let v: serde_json::Value = serde_json::from_str(&r.to_json().unwrap()).unwrap();
        assert_eq!(v["status"], "failed");
        assert_eq!(v["error"]["code"], "not_found");
    }

    #[test]
    fn calc_runs_via_registry() {
        let r = execute("calc", serde_json::json!({"expression": "2 + 2 * 3"}));
        let v: serde_json::Value = serde_json::from_str(&r.to_json().unwrap()).unwrap();
        assert_eq!(v["status"], "success");
        assert_eq!(v["result"]["data"]["result"], 8);
        assert_eq!(v["meta"]["credits_charged"], 0.0);
    }

    #[test]
    fn full_id_routes_to_non_default_operation() {
        // A raw-tool id reaches a sub-operation the base default would never hit.
        let r = execute("calc.base_convert", serde_json::json!({"value": "255", "to_base": 16}));
        let v: serde_json::Value = serde_json::from_str(&r.to_json().unwrap()).unwrap();
        assert_eq!(v["status"], "success");
        assert_eq!(v["result"]["data"]["result"], "ff");
        // The envelope skill stays the BASE name, identical to the server calling
        // execute_free_tool("calc", { .., operation: "base_convert" }).
        assert_eq!(v["skill"], "calc.run");
    }

    #[test]
    fn id_operation_overrides_one_in_params() {
        // Server parity: `{**args, "operation": operation}` — the id wins.
        let r = execute(
            "calc.base_convert",
            serde_json::json!({"operation": "evaluate", "value": "255", "to_base": 16}),
        );
        let v: serde_json::Value = serde_json::from_str(&r.to_json().unwrap()).unwrap();
        assert_eq!(v["status"], "success");
        assert_eq!(v["result"]["data"]["result"], "ff");
    }

    #[test]
    fn bare_base_name_still_uses_the_tool_default() {
        // No dot -> params untouched -> calc's own `evaluate` default applies.
        let r = execute("calc", serde_json::json!({"expression": "6 / 2"}));
        let v: serde_json::Value = serde_json::from_str(&r.to_json().unwrap()).unwrap();
        assert_eq!(v["status"], "success");
        assert_eq!(v["result"]["data"]["result"], 3);
    }

    #[test]
    fn unknown_base_in_a_full_id_is_not_found() {
        let r = execute("nope.thing", serde_json::json!({}));
        let v: serde_json::Value = serde_json::from_str(&r.to_json().unwrap()).unwrap();
        assert_eq!(v["status"], "failed");
        assert_eq!(v["error"]["code"], "not_found");
    }

    #[test]
    fn unknown_operation_in_a_full_id_is_invalid_input() {
        // Known base, bogus operation -> the base tool's own "unknown operation"
        // error, exactly as the server would surface it.
        let r = execute("calc.bogus", serde_json::json!({}));
        let v: serde_json::Value = serde_json::from_str(&r.to_json().unwrap()).unwrap();
        assert_eq!(v["status"], "failed");
        assert_eq!(v["error"]["code"], "invalid_input");
    }
}

