// @generated by scripts/vendor_free_tools.sh — DO NOT EDIT.
// Source of truth: faro-core/core-free/src/. Edit there and re-run the script;
// the core-sync CI job fails if this vendored copy drifts.

//! Free / local tools: deterministic, zero-cost capabilities that run in-process
//! and identically on server and device (SKILL_LAYER_STRATEGY.md §3.2/§8). These
//! are "mostly code, not LLM instructions," so they ship open and local. Step 0
//! seeds two (calc, units) to prove the path end-to-end; the local-pack wave ports
//! the rest of the free computational catalog here.
//!
//! Every tool returns the normalized envelope (Spec 1), so a free tool and a
//! charged skill are indistinguishable to the calling model.

mod astronomy;
mod calc;
mod datetime;
mod encoding;
mod phone;
mod random;
mod timer;
mod timezone;
mod units;

use crate::free::envelope::{Meta, SkillResult};
use crate::free::error::CoreError;

/// Names of the free tools available in this build.
pub fn available() -> Vec<&'static str> {
    vec!["astronomy", "calc", "datetime", "encoding", "phone", "random", "timer", "timezone", "units"]
}

/// Execute a free tool by name with JSON `params`, returning a `SkillResult`
/// envelope. Errors are mapped to buyer-safe envelope errors, never panics.
pub fn execute(name: &str, params: serde_json::Value) -> SkillResult {
    let skill = format!("{name}.run");
    let started = now_ms();
    let outcome = match name {
        "astronomy" => astronomy::run(params),
        "calc" => calc::run(params),
        "datetime" => datetime::run(params),
        "encoding" => encoding::run(params),
        "phone" => phone::run(params),
        "random" => random::run(params),
        "timer" => timer::run(params),
        "timezone" => timezone::run(params),
        "units" => units::run(params),
        other => Err(CoreError::UnknownTool(other.to_string())),
    };
    let latency = now_ms().saturating_sub(started);
    match outcome {
        Ok((data, summary)) => SkillResult::information(&skill, data)
            .with_summary(summary)
            .with_meta(Meta { credits_charged: Some(0.0), latency_ms: Some(latency), ..Default::default() }),
        Err(e) => SkillResult::error(&skill, e.code(), e.to_string(), e.retryable())
            .with_meta(Meta { credits_charged: Some(0.0), latency_ms: Some(latency), ..Default::default() }),
    }
}

/// Each free tool returns its information `data` plus a one-line `summary`.
pub(crate) type ToolOutput = Result<(serde_json::Value, String), CoreError>;

#[cfg(not(test))]
fn now_ms() -> u64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_millis() as u64).unwrap_or(0)
}

// Deterministic clock under test so latency_ms assertions don't flake.
#[cfg(test)]
fn now_ms() -> u64 {
    0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unknown_tool_is_not_found_error() {
        let r = execute("nope", serde_json::json!({}));
        let v: serde_json::Value = serde_json::from_str(&r.to_json().unwrap()).unwrap();
        assert_eq!(v["status"], "failed");
        assert_eq!(v["error"]["code"], "not_found");
    }

    #[test]
    fn calc_runs_via_registry() {
        let r = execute("calc", serde_json::json!({"expression": "2 + 2 * 3"}));
        let v: serde_json::Value = serde_json::from_str(&r.to_json().unwrap()).unwrap();
        assert_eq!(v["status"], "success");
        assert_eq!(v["result"]["data"]["result"], 8);
        assert_eq!(v["meta"]["credits_charged"], 0.0);
    }
}

