// @generated by scripts/vendor_free_tools.sh — DO NOT EDIT.
// Source of truth: faro-core/core-free/src/. Edit there and re-run the script;
// the core-sync CI job fails if this vendored copy drifts.

//! `phone`: parse, validate, and format phone numbers via Google's libphonenumber
//! metadata (Rust `phonenumber` crate). A free tool — deterministic, in-core.
//! Two operations, dispatched on `operation` (default `parse`):
//!   - `parse`   validate + emit canonical formats (E.164, international, national, RFC3966)
//!   - `format`  reformat a number in a specific mode

use crate::free::error::CoreError;
use super::ToolOutput;
use phonenumber::{Mode, PhoneNumber, country, metadata::DATABASE};

pub(crate) fn run(params: serde_json::Value) -> ToolOutput {
    let op = params.get("operation").and_then(|v| v.as_str()).unwrap_or("parse");
    match op {
        "parse" => parse_op(&params),
        "format" => format_op(&params),
        other => Err(CoreError::InvalidInput(format!(
            "unknown operation `{other}` (parse, format)"
        ))),
    }
}

// ---- shared helpers ---------------------------------------------------------

fn parse_number(params: &serde_json::Value) -> Result<PhoneNumber, CoreError> {
    let number = params.get("number")
        .and_then(|v| v.as_str())
        .filter(|s| !s.is_empty())
        .ok_or_else(|| CoreError::InvalidInput("`number` is required (a phone number string)".into()))?;

    let region: Option<country::Id> = params.get("region")
        .and_then(|v| v.as_str())
        .filter(|s| s.len() == 2)
        .and_then(|s| s.parse().ok());

    phonenumber::parse(region, number)
        .map_err(|e| CoreError::InvalidInput(format!(
            "could not parse phone number: {e}. Pass an international number (+country code) or set `region`."
        )))
}

fn format_str(num: &PhoneNumber, mode: Mode) -> String {
    format!("{}", num.format().mode(mode))
}

fn type_name(t: phonenumber::Type) -> &'static str {
    use phonenumber::Type;
    match t {
        Type::FixedLine => "fixed_line",
        Type::Mobile => "mobile",
        Type::FixedLineOrMobile => "fixed_line_or_mobile",
        Type::TollFree => "toll_free",
        Type::PremiumRate => "premium_rate",
        Type::SharedCost => "shared_cost",
        Type::Voip => "voip",
        Type::PersonalNumber => "personal_number",
        Type::Pager => "pager",
        Type::Uan => "uan",
        Type::Emergency => "emergency",
        Type::Voicemail => "voicemail",
        Type::ShortCode => "short_code",
        Type::StandardRate => "standard_rate",
        _ => "unknown",
    }
}

// ---- parse ------------------------------------------------------------------

fn parse_op(params: &serde_json::Value) -> ToolOutput {
    let num = parse_number(params)?;
    let db = &*DATABASE;

    let valid = num.is_valid_with(db);
    let e164 = format_str(&num, Mode::E164);
    let international = format_str(&num, Mode::International);
    let national = format_str(&num, Mode::National);
    let rfc3966 = format_str(&num, Mode::Rfc3966);

    let country_code = num.country().code();
    let region_code = num.country().id().map(|id| format!("{id:?}"));
    let number_type = type_name(num.number_type(db));

    let data = serde_json::json!({
        "valid": valid,
        "e164": e164,
        "international": international,
        "national": national,
        "rfc3966": rfc3966,
        "country_code": country_code,
        "region_code": region_code,
        "number_type": number_type,
    });
    let summary = if valid {
        format!("{e164} ({number_type})")
    } else {
        format!("{e164} (invalid)")
    };
    Ok((data, summary))
}

// ---- format -----------------------------------------------------------------

fn format_op(params: &serde_json::Value) -> ToolOutput {
    let num = parse_number(params)?;
    let fmt = params.get("format").and_then(|v| v.as_str()).unwrap_or("e164").to_lowercase();
    let mode = match fmt.as_str() {
        "e164" => Mode::E164,
        "international" => Mode::International,
        "national" => Mode::National,
        "rfc3966" => Mode::Rfc3966,
        other => return Err(CoreError::InvalidInput(format!(
            "unknown format `{other}` (e164, international, national, rfc3966)"
        ))),
    };
    let db = &*DATABASE;
    let valid = num.is_valid_with(db);
    let result = format_str(&num, mode);
    let data = serde_json::json!({"format": fmt, "result": result, "valid": valid});
    Ok((data, result.clone()))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn p(number: &str, region: Option<&str>) -> serde_json::Value {
        let mut params = serde_json::json!({"number": number});
        if let Some(r) = region {
            params["region"] = serde_json::json!(r);
        }
        parse_op(&params).unwrap().0
    }

    #[test]
    fn us_number_valid() {
        let d = p("+12025551234", None);
        assert_eq!(d["valid"], true);
        assert_eq!(d["country_code"], 1);
        assert!(d["e164"].as_str().unwrap().starts_with("+1202"));
    }

    #[test]
    fn uk_with_region_hint() {
        let d = p("07400123456", Some("GB"));
        assert_eq!(d["valid"], true);
        assert!(d["region_code"].as_str().unwrap().contains("GB"));
        assert_eq!(d["number_type"], "mobile");
    }

    #[test]
    fn format_modes() {
        let d = format_op(&serde_json::json!({"number": "+442071838750", "format": "national"})).unwrap().0;
        assert!(!d["result"].as_str().unwrap().starts_with('+'));

        let d = format_op(&serde_json::json!({"number": "+442071838750", "format": "e164"})).unwrap().0;
        assert!(d["result"].as_str().unwrap().starts_with('+'));
    }

    #[test]
    fn parse_error_on_garbage() {
        assert!(parse_op(&serde_json::json!({"number": "not-a-phone"})).is_err());
        assert!(parse_op(&serde_json::json!({})).is_err());
    }
}
