// @generated by scripts/vendor_free_tools.sh — DO NOT EDIT.
// Source of truth: faro-core/core-free/src/. Edit there and re-run the script;
// the core-sync CI job fails if this vendored copy drifts.

//! `random`: cryptographically-strong random integers, choices, shuffles, and
//! strings (CSPRNG via getrandom). Free/local, dispatches on `operation`. Mirrors
//! the server `internal_tools/random_tools.py` contract. Intentionally
//! non-deterministic (an LLM cannot produce uniform unpredictable values).

use super::ToolOutput;
use crate::free::error::CoreError;

fn rand_u64() -> Result<u64, CoreError> {
    let mut b = [0u8; 8];
    getrandom::getrandom(&mut b).map_err(|_| CoreError::InvalidInput("randomness unavailable".into()))?;
    Ok(u64::from_le_bytes(b))
}

/// Uniform integer in [0, n) without modulo bias (rejection sampling).
fn below(n: u64) -> Result<u64, CoreError> {
    if n == 0 { return Ok(0); }
    let zone = u64::MAX - (u64::MAX % n);
    loop {
        let r = rand_u64()?;
        if r < zone { return Ok(r % n); }
    }
}

pub(crate) fn run(params: serde_json::Value) -> ToolOutput {
    let op = params.get("operation").and_then(|v| v.as_str()).unwrap_or("").to_lowercase();
    match op.as_str() {
        "integer" => integer(&params),
        "choice" => choice(&params),
        "shuffle" => shuffle(&params),
        "string" => string_op(&params),
        "" => Err(CoreError::InvalidInput("missing `operation` (integer, choice, shuffle, string)".into())),
        other => Err(CoreError::InvalidInput(format!("unknown operation `{other}`"))),
    }
}

fn count_arg(params: &serde_json::Value, default: i64, cap: i64) -> usize {
    params.get("count").and_then(|v| v.as_i64()).unwrap_or(default).clamp(1, cap) as usize
}

fn integer(params: &serde_json::Value) -> ToolOutput {
    let lo = params.get("min").and_then(|v| v.as_i64())
        .ok_or_else(|| CoreError::InvalidInput("`min` must be an integer".into()))?;
    let hi = params.get("max").and_then(|v| v.as_i64())
        .ok_or_else(|| CoreError::InvalidInput("`max` must be an integer".into()))?;
    if hi < lo { return Err(CoreError::InvalidInput("`max` must be >= `min`".into())); }
    let count = count_arg(params, 1, 1000);
    let span = (hi - lo) as u64 + 1;
    let mut values = Vec::with_capacity(count);
    for _ in 0..count { values.push(lo + below(span)? as i64); }
    Ok((serde_json::json!({"min": lo, "max": hi, "count": count, "values": values}), format!("{count} random integer(s)")))
}

fn choice(params: &serde_json::Value) -> ToolOutput {
    let items = params.get("items").and_then(|v| v.as_array())
        .filter(|a| !a.is_empty())
        .ok_or_else(|| CoreError::InvalidInput("`items` must be a non-empty array".into()))?;
    let unique = params.get("unique").and_then(|v| v.as_bool()).unwrap_or(false);
    let selected: Vec<serde_json::Value> = if unique {
        let count = params.get("count").and_then(|v| v.as_i64()).unwrap_or(1).max(1) as usize;
        if count > items.len() {
            return Err(CoreError::InvalidInput("`count` cannot exceed the number of items when `unique` is true".into()));
        }
        // Partial Fisher-Yates over indices.
        let mut idx: Vec<usize> = (0..items.len()).collect();
        for i in 0..count {
            let j = i + below((items.len() - i) as u64)? as usize;
            idx.swap(i, j);
        }
        idx[..count].iter().map(|&i| items[i].clone()).collect()
    } else {
        let count = count_arg(params, 1, 1000);
        let mut out = Vec::with_capacity(count);
        for _ in 0..count { out.push(items[below(items.len() as u64)? as usize].clone()); }
        out
    };
    Ok((serde_json::json!({"count": selected.len(), "unique": unique, "selected": selected}), format!("{} selection(s)", selected.len())))
}

fn shuffle(params: &serde_json::Value) -> ToolOutput {
    let items = params.get("items").and_then(|v| v.as_array())
        .ok_or_else(|| CoreError::InvalidInput("`items` must be an array".into()))?;
    let mut out = items.clone();
    let n = out.len();
    for i in (1..n).rev() {
        let j = below((i + 1) as u64)? as usize;
        out.swap(i, j);
    }
    Ok((serde_json::json!({"count": out.len(), "shuffled": out}), format!("shuffled {n} item(s)")))
}

fn charset(name: &str) -> Option<&'static str> {
    match name {
        "alphanumeric" => Some("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"),
        "alphabetic" => Some("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"),
        "lowercase" => Some("abcdefghijklmnopqrstuvwxyz"),
        "uppercase" => Some("ABCDEFGHIJKLMNOPQRSTUVWXYZ"),
        "numeric" => Some("0123456789"),
        "hex" => Some("0123456789abcdef"),
        "ascii_printable" => Some("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"),
        _ => None,
    }
}

fn string_op(params: &serde_json::Value) -> ToolOutput {
    let length = params.get("length").and_then(|v| v.as_i64()).unwrap_or(16).clamp(1, 256) as usize;
    let chars: Vec<char> = if let Some(a) = params.get("alphabet").and_then(|v| v.as_str()).filter(|s| !s.is_empty()) {
        a.chars().collect()
    } else {
        let cs = params.get("charset").and_then(|v| v.as_str()).unwrap_or("alphanumeric").to_lowercase();
        charset(&cs).ok_or_else(|| CoreError::InvalidInput("unknown `charset`".into()))?.chars().collect()
    };
    let mut s = String::with_capacity(length);
    for _ in 0..length { s.push(chars[below(chars.len() as u64)? as usize]); }
    Ok((serde_json::json!({"length": length, "value": s}), format!("{length}-char string")))
}

#[cfg(test)]
mod tests {
    use super::*;
    fn d(v: serde_json::Value) -> serde_json::Value { run(v).unwrap().0 }
    #[test] fn integer_in_range() {
        let r = d(serde_json::json!({"operation":"integer","min":1,"max":6,"count":50}));
        for v in r["values"].as_array().unwrap() { let n=v.as_i64().unwrap(); assert!((1..=6).contains(&n)); }
    }
    #[test] fn choice_unique_no_repeat() {
        let r = d(serde_json::json!({"operation":"choice","items":[1,2,3,4],"count":4,"unique":true}));
        let mut got: Vec<i64> = r["selected"].as_array().unwrap().iter().map(|x| x.as_i64().unwrap()).collect();
        got.sort(); assert_eq!(got, vec![1,2,3,4]);
    }
    #[test] fn string_len_and_charset() {
        let r = d(serde_json::json!({"operation":"string","length":12,"charset":"hex"}));
        let v = r["value"].as_str().unwrap();
        assert_eq!(v.len(), 12);
        assert!(v.chars().all(|c| "0123456789abcdef".contains(c)));
    }
    #[test] fn shuffle_preserves_multiset() {
        let r = d(serde_json::json!({"operation":"shuffle","items":[1,2,3,3]}));
        let mut got: Vec<i64> = r["shuffled"].as_array().unwrap().iter().map(|x| x.as_i64().unwrap()).collect();
        got.sort(); assert_eq!(got, vec![1,2,3,3]);
    }
}
