// @generated by scripts/vendor_free_tools.sh — DO NOT EDIT.
// Source of truth: faro-core/core-free/src/. Edit there and re-run the script;
// the core-sync CI job fails if this vendored copy drifts.

//! `timezone`: current time, conversion between IANA zones, and offset/DST facts,
//! resolved from `jiff`'s time-zone database (system tzdata with a bundled
//! platform fallback). Free/local, dispatches on `operation`. Single source of
//! truth for the server `timezone` namespace too (the Python
//! `internal_tools/timezone.py` it replaces).

use jiff::civil::{Date, DateTime};
use jiff::tz::{Dst, Offset, TimeZone};
use jiff::{Timestamp, Zoned};

use super::ToolOutput;
use crate::free::error::CoreError;

fn invalid(msg: impl Into<String>) -> CoreError {
    CoreError::InvalidInput(msg.into())
}

fn parse_zone(name: Option<&str>, field: &str) -> Result<TimeZone, CoreError> {
    let n = name.map(str::trim).filter(|s| !s.is_empty())
        .ok_or_else(|| invalid(format!("`{field}` is required (IANA name, e.g. Europe/London)")))?;
    TimeZone::get(n).map_err(|_| invalid(format!("unknown timezone `{n}`; use list_timezones for valid IANA names")))
}

/// Like `parse_zone`, but a missing/empty name defaults to UTC instead of
/// erroring. `current_time` uses this so "what day/time is it" answers with no
/// arguments — the caller often has no IANA zone to hand — while a supplied zone
/// still localizes. A wrong zone is still rejected; only absence is lenient.
fn parse_zone_or_utc(name: Option<&str>) -> Result<TimeZone, CoreError> {
    match name.map(str::trim).filter(|s| !s.is_empty()) {
        Some(n) => TimeZone::get(n)
            .map_err(|_| invalid(format!("unknown timezone `{n}`; use list_timezones for valid IANA names"))),
        None => Ok(TimeZone::UTC),
    }
}

fn fmt_offset(total_secs: i32) -> String {
    let sign = if total_secs >= 0 { "+" } else { "-" };
    let a = total_secs.unsigned_abs();
    format!("{sign}{:02}:{:02}", a / 3600, (a % 3600) / 60)
}

fn out_dt(z: &Zoned) -> String {
    z.strftime("%Y-%m-%dT%H:%M:%S%:z").to_string()
}

/// Offset / DST / abbreviation for a zoned instant, matching the server's
/// `_describe`.
fn describe(z: &Zoned) -> serde_json::Value {
    let info = z.time_zone().to_offset_info(z.timestamp());
    let secs = info.offset().seconds();
    serde_json::json!({
        "utc_offset": fmt_offset(secs),
        "utc_offset_seconds": secs,
        "dst_active": matches!(info.dst(), Dst::Yes),
        "abbreviation": info.abbreviation(),
    })
}

fn merge(into: &mut serde_json::Value, from: serde_json::Value) {
    if let (Some(a), Some(b)) = (into.as_object_mut(), from.as_object()) {
        for (k, v) in b {
            a.insert(k.clone(), v.clone());
        }
    }
}

fn s<'a>(p: &'a serde_json::Value, k: &str) -> Option<&'a str> {
    p.get(k).and_then(|v| v.as_str())
}

pub(crate) fn run(params: serde_json::Value) -> ToolOutput {
    match params.get("operation").and_then(|v| v.as_str()).unwrap_or("") {
        "current_time" => current_time(&params),
        "convert" => convert(&params),
        "zone_info" => zone_info(&params),
        "list_timezones" => list_timezones(&params),
        "" => Err(invalid("missing `operation` (current_time, convert, zone_info, list_timezones)")),
        other => Err(invalid(format!("unknown operation `{other}`"))),
    }
}

fn zone_label(tz: &TimeZone) -> String {
    tz.iana_name().unwrap_or("").to_string()
}

fn current_time(p: &serde_json::Value) -> ToolOutput {
    let tz = parse_zone_or_utc(s(p, "timezone"))?;
    let now = Timestamp::now().to_zoned(tz.clone());
    let utc = now.timestamp().to_zoned(TimeZone::UTC);
    let mut data = serde_json::json!({
        "timezone": zone_label(&tz),
        "datetime": out_dt(&now),
        "date": now.strftime("%Y-%m-%d").to_string(),
        "time": now.strftime("%H:%M:%S").to_string(),
        "day_of_week": now.strftime("%A").to_string(),
        "utc_datetime": out_dt(&utc),
        "unix": now.timestamp().as_second(),
    });
    merge(&mut data, describe(&now));
    Ok((data, format!("{} now", zone_label(&tz))))
}

/// A parsed `datetime` input: a naive wall-clock, or an instant fixed by an
/// explicit offset (which we keep so the source can be reported faithfully).
enum Parsed {
    Naive(DateTime),
    Aware { instant: Timestamp, offset_secs: i32 },
}

fn parse_input(v: Option<&str>) -> Result<Parsed, CoreError> {
    let t = v.map(str::trim).filter(|x| !x.is_empty())
        .ok_or_else(|| invalid("`datetime` is required (ISO 8601, e.g. 2026-06-06T14:30:00)"))?;
    if let Ok(ts) = t.parse::<Timestamp>() {
        return Ok(Parsed::Aware { instant: ts, offset_secs: parse_offset_suffix(t)? });
    }
    let norm = t.replacen(' ', "T", 1);
    if let Ok(dt) = norm.parse::<DateTime>() {
        return Ok(Parsed::Naive(dt));
    }
    if let Ok(d) = t.parse::<Date>() {
        return Ok(Parsed::Naive(d.at(0, 0, 0, 0)));
    }
    Err(invalid("`datetime` must be ISO 8601 (e.g. 2026-06-06T14:30:00)"))
}

/// Pull the UTC offset (in seconds) out of an already-validated RFC 3339 string.
fn parse_offset_suffix(s: &str) -> Result<i32, CoreError> {
    if s.ends_with('Z') || s.ends_with('z') {
        return Ok(0);
    }
    let tpos = s.find(['T', ' ']).unwrap_or(0);
    let tail = &s[tpos..];
    let i = tail.rfind(['+', '-']).ok_or_else(|| invalid("missing offset"))?;
    let sign = if tail.as_bytes()[i] == b'+' { 1 } else { -1 };
    let digits: String = tail[i + 1..].chars().filter(|c| c.is_ascii_digit()).collect();
    let (h, m) = match digits.len() {
        2 => (digits.parse::<i32>().unwrap_or(0), 0),
        4 => (digits[0..2].parse().unwrap_or(0), digits[2..4].parse().unwrap_or(0)),
        _ => return Err(invalid("bad offset")),
    };
    Ok(sign * (h * 3600 + m * 60))
}

fn convert(p: &serde_json::Value) -> ToolOutput {
    let to = parse_zone(s(p, "to_timezone"), "to_timezone")?;
    let from_name = s(p, "from_timezone");
    let (src, source) = match parse_input(s(p, "datetime"))? {
        Parsed::Naive(dt) => {
            // Interpret the wall-clock in from_timezone.
            let from = parse_zone(from_name, "from_timezone")?;
            let z = from.to_zoned(dt).map_err(|_| invalid("ambiguous or nonexistent local time in from_timezone"))?;
            let mut source = serde_json::json!({"timezone": zone_label(&from), "datetime": out_dt(&z)});
            merge(&mut source, describe(&z));
            (z, source)
        }
        Parsed::Aware { instant, offset_secs } => {
            // The explicit offset fixes the instant; report it as a fixed offset,
            // labelled by from_timezone if the caller supplied one.
            let off = Offset::from_seconds(offset_secs).map_err(|_| invalid("offset out of range"))?;
            let z = instant.to_zoned(TimeZone::fixed(off));
            let label = from_name.map(str::to_string).unwrap_or_else(|| fmt_offset(offset_secs));
            let source = serde_json::json!({
                "timezone": label,
                "datetime": out_dt(&z),
                "utc_offset": fmt_offset(offset_secs),
                "utc_offset_seconds": offset_secs,
                "dst_active": false,
                "abbreviation": format!("UTC{}", fmt_offset(offset_secs)),
            });
            (z, source)
        }
    };
    let tgt = src.timestamp().to_zoned(to.clone());
    let mut target = serde_json::json!({"timezone": zone_label(&to), "datetime": out_dt(&tgt)});
    merge(&mut target, describe(&tgt));
    let data = serde_json::json!({
        "source": source,
        "target": target,
        "utc_datetime": out_dt(&src.timestamp().to_zoned(TimeZone::UTC)),
    });
    Ok((data, format!("{} -> {}", source["timezone"].as_str().unwrap_or(""), zone_label(&to))))
}

fn zone_info(p: &serde_json::Value) -> ToolOutput {
    let tz = parse_zone(s(p, "timezone"), "timezone")?;
    let instant = match s(p, "date") {
        Some(d) => {
            let nd: Date = d.trim().parse().map_err(|_| invalid("`date` must be YYYY-MM-DD"))?;
            // Noon avoids the midnight DST-transition edge for the offset readout.
            tz.to_zoned(nd.at(12, 0, 0, 0)).map_err(|_| invalid("ambiguous local time"))?
        }
        None => Timestamp::now().to_zoned(tz.clone()),
    };
    let mut data = serde_json::json!({"timezone": zone_label(&tz), "as_of": out_dt(&instant)});
    merge(&mut data, describe(&instant));
    Ok((data, format!("{} offset", zone_label(&tz))))
}

fn list_timezones(p: &serde_json::Value) -> ToolOutput {
    let filter = s(p, "query").map(|q| q.to_lowercase());
    let mut zones: Vec<String> = jiff::tz::db().available().map(|n| n.as_str().to_string()).collect();
    zones.sort();
    if let Some(q) = filter.as_ref() {
        zones.retain(|n| n.to_lowercase().contains(q));
    }
    Ok((serde_json::json!({"count": zones.len(), "timezones": zones}), format!("{} zones", zones.len())))
}

#[cfg(test)]
mod tests {
    use super::*;
    fn d(v: serde_json::Value) -> serde_json::Value {
        run(v).unwrap().0
    }

    #[test]
    fn current_has_offset() {
        let r = d(serde_json::json!({"operation":"current_time","timezone":"UTC"}));
        assert_eq!(r["utc_offset"], "+00:00");
        assert_eq!(r["timezone"], "UTC");
        assert_eq!(r["abbreviation"], "UTC");
    }
    #[test]
    fn current_time_defaults_to_utc_when_zone_omitted() {
        // "What day is it today?" must answer with no arguments — a missing zone
        // falls back to UTC rather than erroring (the production failure it fixes).
        let r = d(serde_json::json!({"operation":"current_time"}));
        assert_eq!(r["timezone"], "UTC");
        assert_eq!(r["utc_offset"], "+00:00");
        assert!(r["date"].as_str().is_some_and(|s| s.len() == 10)); // YYYY-MM-DD
        assert!(r["day_of_week"].as_str().is_some());
    }
    #[test]
    fn current_time_still_rejects_a_bad_zone() {
        // Leniency is for absence only; a supplied-but-invalid zone still errors.
        assert!(run(serde_json::json!({"operation":"current_time","timezone":"Mars/Olympus_Mons"})).is_err());
    }
    #[test]
    fn convert_ny_to_london_winter() {
        let r = d(serde_json::json!({"operation":"convert","datetime":"2026-01-15T12:00:00","from_timezone":"America/New_York","to_timezone":"Europe/London"}));
        assert_eq!(r["source"], serde_json::json!({"timezone":"America/New_York","datetime":"2026-01-15T12:00:00-05:00","utc_offset":"-05:00","utc_offset_seconds":-18000,"dst_active":false,"abbreviation":"EST"}));
        assert_eq!(r["target"], serde_json::json!({"timezone":"Europe/London","datetime":"2026-01-15T17:00:00+00:00","utc_offset":"+00:00","utc_offset_seconds":0,"dst_active":false,"abbreviation":"GMT"}));
        assert_eq!(r["utc_datetime"], "2026-01-15T17:00:00+00:00");
    }
    #[test]
    fn convert_ny_to_london_summer() {
        let r = d(serde_json::json!({"operation":"convert","datetime":"2026-07-15T12:00:00","from_timezone":"America/New_York","to_timezone":"Europe/London"}));
        assert_eq!(r["source"]["abbreviation"], "EDT");
        assert_eq!(r["source"]["dst_active"], true);
        assert_eq!(r["target"]["abbreviation"], "BST");
        assert_eq!(r["target"]["datetime"], "2026-07-15T17:00:00+01:00");
        assert_eq!(r["utc_datetime"], "2026-07-15T16:00:00+00:00");
    }
    #[test]
    fn convert_explicit_offset_no_from() {
        let r = d(serde_json::json!({"operation":"convert","datetime":"2026-06-06T14:30:00+05:00","to_timezone":"Asia/Tokyo"}));
        assert_eq!(r["source"], serde_json::json!({"timezone":"+05:00","datetime":"2026-06-06T14:30:00+05:00","utc_offset":"+05:00","utc_offset_seconds":18000,"dst_active":false,"abbreviation":"UTC+05:00"}));
        assert_eq!(r["target"]["datetime"], "2026-06-06T18:30:00+09:00");
        assert_eq!(r["target"]["abbreviation"], "JST");
        assert_eq!(r["utc_datetime"], "2026-06-06T09:30:00+00:00");
    }
    #[test]
    fn convert_explicit_offset_with_from_label() {
        let r = d(serde_json::json!({"operation":"convert","datetime":"2026-06-06T14:30:00+05:00","from_timezone":"Europe/Paris","to_timezone":"Asia/Tokyo"}));
        // The label is from_timezone, but the instant stays fixed at the given offset.
        assert_eq!(r["source"]["timezone"], "Europe/Paris");
        assert_eq!(r["source"]["utc_offset"], "+05:00");
        assert_eq!(r["source"]["abbreviation"], "UTC+05:00");
    }
    #[test]
    fn zone_info_dst() {
        let r = d(serde_json::json!({"operation":"zone_info","timezone":"Europe/London","date":"2026-07-01"}));
        assert_eq!(r, serde_json::json!({"timezone":"Europe/London","as_of":"2026-07-01T12:00:00+01:00","utc_offset":"+01:00","utc_offset_seconds":3600,"dst_active":true,"abbreviation":"BST"}));
    }
    #[test]
    fn zone_info_half_hour_offset() {
        let r = d(serde_json::json!({"operation":"zone_info","timezone":"Asia/Kolkata","date":"2026-06-01"}));
        assert_eq!(r["utc_offset"], "+05:30");
        assert_eq!(r["utc_offset_seconds"], 19800);
        assert_eq!(r["abbreviation"], "IST");
    }
    #[test]
    fn zone_info_lord_howe() {
        let r = d(serde_json::json!({"operation":"zone_info","timezone":"Australia/Lord_Howe","date":"2026-01-01"}));
        assert_eq!(r["utc_offset"], "+11:00");
        assert_eq!(r["dst_active"], true);
        assert_eq!(r["abbreviation"], "+11");
    }
    #[test]
    fn list_filters() {
        let r = d(serde_json::json!({"operation":"list_timezones","query":"london"}));
        assert!(r["timezones"].as_array().unwrap().iter().any(|z| z == "Europe/London"));
    }
}
