// @generated by scripts/vendor_free_tools.sh — DO NOT EDIT.
// Source of truth: faro-core/core-free/src/. Edit there and re-run the script;
// the core-sync CI job fails if this vendored copy drifts.

//! `timer`: a bounded blocking wait. A free tool — runs in-core, no LLM, no
//! charge. One operation, `wait`: pause for the requested number of seconds
//! (capped at 30) and report how long it actually waited.
//!
//! The value over the model alone: an LLM cannot pause or sleep on its own. This
//! holds the call open for the requested duration, letting an agent inject a real
//! delay inline (polling, retry backoff, rate-limiting). Distinct from the
//! `schedule` namespace, which fires a callback LATER without pausing.
//!
//! On the server this is invoked with the GIL released and off the event-loop
//! thread (the PyO3 binding + the orchestrator's free path), so the blocking
//! sleep parks only its own worker, never the loop. On-device the host owns the
//! thread, so a blocking wait is exactly the intent.

use std::time::Duration;

use crate::free::error::CoreError;
use super::ToolOutput;

const MAX_WAIT_SECS: f64 = 30.0; // cap: a wait must not outlive client/proxy timeouts

pub(crate) fn run(params: serde_json::Value) -> ToolOutput {
    match params.get("operation").and_then(|v| v.as_str()).unwrap_or("wait") {
        "wait" => wait(&params),
        other => Err(CoreError::InvalidInput(format!("unknown operation `{other}` (wait)"))),
    }
}

fn wait(params: &serde_json::Value) -> ToolOutput {
    let seconds = params
        .get("seconds")
        .and_then(|v| v.as_f64())
        .ok_or_else(|| CoreError::InvalidInput("`seconds` is required (a number)".into()))?;
    if seconds < 0.0 || !seconds.is_finite() {
        return Err(CoreError::InvalidInput("`seconds` must be >= 0".into()));
    }
    let waited = seconds.min(MAX_WAIT_SECS);
    sleep(waited);
    let data = serde_json::json!({
        "requested_seconds": seconds,
        "waited_seconds": waited,
        "capped": waited < seconds,
        "max_seconds": MAX_WAIT_SECS,
    });
    Ok((data, format!("Waited {waited} second(s).")))
}

#[cfg(not(test))]
fn sleep(seconds: f64) {
    std::thread::sleep(Duration::from_secs_f64(seconds));
}

// Don't actually block the test suite; the duration is computed from the input,
// not the clock, so shape and capping are fully testable without sleeping.
#[cfg(test)]
fn sleep(_seconds: f64) {
    let _ = Duration::from_secs_f64(_seconds);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn waits_and_reports() {
        let (d, _) = wait(&serde_json::json!({"seconds": 2})).unwrap();
        assert_eq!(d["requested_seconds"], 2.0);
        assert_eq!(d["waited_seconds"], 2.0);
        assert_eq!(d["capped"], false);
    }

    #[test]
    fn caps_at_thirty() {
        let (d, _) = wait(&serde_json::json!({"seconds": 120})).unwrap();
        assert_eq!(d["waited_seconds"], 30.0);
        assert_eq!(d["capped"], true);
    }

    #[test]
    fn rejects_bad_input() {
        assert!(wait(&serde_json::json!({"seconds": -1})).is_err());
        assert!(wait(&serde_json::json!({})).is_err());
    }
}
