// @generated by scripts/vendor_free_tools.sh — DO NOT EDIT.
// Source of truth: faro-core/core-free/src/. Edit there and re-run the script;
// the core-sync CI job fails if this vendored copy drifts.

//! `units`: physical unit conversion backed by rink-core's full dimensional
//! registry. A free tool — deterministic, in-core, no network. Two operations:
//!   - `convert`     convert a value between compatible units
//!   - `list_units`  list common units per dimension (optionally filtered)
//!
//! The query for `convert` is built as "<value> <from_unit> -> <to_unit>" and
//! sent to rink-core. The response is parsed to extract the numeric result;
//! the formatted string from rink is also returned as `formatted`.

use std::sync::OnceLock;

use crate::free::error::CoreError;
use super::ToolOutput;

// rink-core's Context is expensive to build (~30ms, reads bundled unit
// definitions). Build once, reuse via a global. It is NOT Send+Sync so we
// wrap it in a Mutex.
static CTX: OnceLock<std::sync::Mutex<rink_core::Context>> = OnceLock::new();

fn with_ctx<F, T>(f: F) -> T
where
    F: FnOnce(&mut rink_core::Context) -> T,
{
    let mutex = CTX.get_or_init(|| {
        let ctx = rink_core::simple_context().expect("rink-core unit definitions failed to load");
        std::sync::Mutex::new(ctx)
    });
    let mut guard = mutex.lock().unwrap_or_else(|e| e.into_inner());
    f(&mut *guard)
}

pub(crate) fn run(params: serde_json::Value) -> ToolOutput {
    let op = params.get("operation").and_then(|v| v.as_str()).unwrap_or("convert");
    match op {
        "convert" => convert(&params),
        "list_units" => list_units(&params),
        other => Err(CoreError::InvalidInput(format!(
            "unknown operation `{other}` (convert, list_units)"
        ))),
    }
}

// ---- convert ----------------------------------------------------------------

fn convert(params: &serde_json::Value) -> ToolOutput {
    let value = params
        .get("value")
        .and_then(|v| v.as_f64())
        .ok_or_else(|| CoreError::InvalidInput("missing numeric field `value`".into()))?;
    let from = params
        .get("from_unit")
        .and_then(|v| v.as_str())
        .filter(|s| !s.is_empty())
        .ok_or_else(|| CoreError::InvalidInput("missing string field `from_unit`".into()))?;
    let to = params
        .get("to_unit")
        .and_then(|v| v.as_str())
        .filter(|s| !s.is_empty())
        .ok_or_else(|| CoreError::InvalidInput("missing string field `to_unit`".into()))?;

    // Build the rink query: "<value> <from> -> <to>"
    let query = format!("{value} {from} -> {to}");
    let raw = with_ctx(|ctx| rink_core::one_line(ctx, &query))
        .map_err(|e| CoreError::InvalidInput(clean_rink_error(&e, from, to)))?;

    // Parse the numeric result from rink's output, e.g.:
    //   "4.828032 kilometer (length)"
    //   "approx. 2.204622 pound (mass)"
    //   "212 °F (temperature)"
    let result = parse_rink_number(&raw);

    let data = serde_json::json!({
        "value": value,
        "from_unit": from,
        "to_unit": to,
        "result": result,
        "formatted": raw,
    });
    let summary = format!("{value} {from} = {raw}");
    Ok((data, summary))
}

/// Map rink-core's raw error strings into clean, buyer-facing messages. rink
/// leaks implementation detail (the phrase "Conformance error", its internal
/// "Suggestions:" multipliers like `linear_density`, etc.) that must never reach
/// a customer. We recognise the two cases that matter and otherwise fall back to
/// a generic, leak-free message.
fn clean_rink_error(err: &str, from: &str, to: &str) -> String {
    // Unknown unit: rink emits `No such unit <got>[, did you mean <x>?]`.
    if let Some(idx) = err.find("No such unit ") {
        let rest = &err[idx + "No such unit ".len()..];
        let unit = rest
            .split(',')
            .next()
            .unwrap_or(rest)
            .trim()
            .trim_matches('"')
            .trim();
        return format!("unknown unit: {unit}");
    }
    // Incompatible dimensions: rink emits a multi-line "Conformance error" with
    // the dimension names in parentheses (e.g. "1 meter (length)").
    if err.contains("Conformance error") {
        return match extract_dims(err) {
            Some((left, right)) => format!(
                "cannot convert {from} to {to}: incompatible dimensions ({left} vs {right})"
            ),
            None => format!("cannot convert {from} to {to}: incompatible dimensions"),
        };
    }
    format!("cannot convert {from} to {to}")
}

/// Pull the first two parenthesised dimension names out of a conformance error,
/// e.g. "1 meter (length) != 1 kilogram (mass)" -> ("length", "mass").
fn extract_dims(err: &str) -> Option<(String, String)> {
    let mut dims = err.match_indices('(').filter_map(|(i, _)| {
        err[i + 1..].find(')').map(|j| err[i + 1..i + 1 + j].to_string())
    });
    let left = dims.next()?;
    let right = dims.next()?;
    Some((left, right))
}

/// Extract the leading number from rink's output string. Returns null if it
/// can't be parsed (the formatted string still carries the answer).
fn parse_rink_number(s: &str) -> serde_json::Value {
    // Strip "approx. " prefix if present.
    let s = s.trim_start_matches("approx. ").trim();
    // Take everything up to the first space (the number part).
    let num_str = s.split_whitespace().next().unwrap_or("");
    // Remove any trailing commas or punctuation.
    let num_str = num_str.trim_end_matches(',');
    if let Ok(v) = num_str.parse::<f64>() {
        if v.fract() == 0.0 && v.abs() < 1e15 {
            return serde_json::json!(v as i64);
        }
        return serde_json::json!(v);
    }
    serde_json::Value::Null
}

// ---- list_units -------------------------------------------------------------

/// Common units per dimension. Not exhaustive — rink-core knows thousands more
/// (SI prefixes, obscure historic units, etc.) — but covers the everyday set.
static COMMON: &[(&str, &[&str])] = &[
    ("length", &["meter", "kilometer", "centimeter", "millimeter", "micrometer",
                 "mile", "yard", "foot", "inch", "nautical_mile", "light_year"]),
    ("mass", &["kilogram", "gram", "milligram", "metric_ton", "pound", "ounce", "stone"]),
    ("time", &["second", "minute", "hour", "day", "week", "year"]),
    ("temperature", &["kelvin", "celsius", "fahrenheit"]),
    ("area", &["square_meter", "square_kilometer", "hectare", "acre", "square_mile", "square_foot"]),
    ("volume", &["liter", "milliliter", "cubic_meter", "gallon", "quart", "pint", "cup", "fluid_ounce"]),
    ("speed", &["meter_per_second", "kilometer_per_hour", "mile_per_hour", "knot", "foot_per_second"]),
    ("data", &["bit", "byte", "kilobyte", "megabyte", "gigabyte", "terabyte", "kibibyte", "mebibyte", "gibibyte"]),
    ("energy", &["joule", "kilojoule", "calorie", "kilocalorie", "watt_hour", "kilowatt_hour", "electron_volt"]),
    ("pressure", &["pascal", "kilopascal", "bar", "atmosphere", "psi", "torr"]),
    ("power", &["watt", "kilowatt", "megawatt", "horsepower"]),
    ("angle", &["radian", "degree", "gradian"]),
];

fn list_units(params: &serde_json::Value) -> ToolOutput {
    let query = params.get("query").and_then(|v| v.as_str()).unwrap_or("").to_lowercase();

    let mut dimensions = serde_json::Map::new();
    for (dim, units) in COMMON {
        if query.is_empty() || dim.contains(query.as_str()) {
            let arr: Vec<serde_json::Value> = units.iter().map(|u| serde_json::json!(u)).collect();
            dimensions.insert(dim.to_string(), serde_json::Value::Array(arr));
        } else {
            let matched: Vec<serde_json::Value> = units.iter()
                .filter(|u| u.contains(query.as_str()))
                .map(|u| serde_json::json!(u))
                .collect();
            if !matched.is_empty() {
                dimensions.insert(dim.to_string(), serde_json::Value::Array(matched));
            }
        }
    }

    let data = serde_json::json!({
        "dimensions": dimensions,
        "note": "rink-core also accepts SI prefixes and many more unit names; these are the common ones.",
    });
    let summary = format!("{} dimension(s) listed", dimensions.len());
    Ok((data, summary))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn conv(value: f64, from: &str, to: &str) -> serde_json::Value {
        convert(&serde_json::json!({"value": value, "from_unit": from, "to_unit": to})).unwrap().0
    }

    #[test]
    fn length_conversions() {
        let d = conv(3.0, "miles", "km");
        // rink: 3 miles -> km is 4.828032 km
        let r = d["result"].as_f64().unwrap();
        assert!((r - 4.828032).abs() < 0.0001, "got {r}");
    }

    #[test]
    fn temperature_conversion() {
        let d = conv(100.0, "celsius", "fahrenheit");
        // 100°C = 212°F
        let r = d["result"].as_i64().unwrap_or(d["result"].as_f64().unwrap() as i64);
        assert_eq!(r, 212);
    }

    #[test]
    fn mass_conversion() {
        let d = conv(1.0, "kg", "lb");
        let r = d["result"].as_f64().unwrap();
        assert!((r - 2.2046).abs() < 0.001, "got {r}");
    }

    #[test]
    fn incompatible_dimensions_error() {
        let err = convert(&serde_json::json!({"value": 1.0, "from_unit": "meter", "to_unit": "kg"}))
            .unwrap_err()
            .to_string();
        // Clean buyer-facing copy: no rink internals leaked.
        assert_eq!(
            err,
            "invalid input: cannot convert meter to kg: incompatible dimensions (length vs mass)"
        );
        assert!(!err.contains("Conformance"), "leaked rink internals: {err}");
        assert!(!err.contains("linear_density"), "leaked rink suggestions: {err}");
        assert!(!err.contains("Suggestions"), "leaked rink suggestions: {err}");
    }

    #[test]
    fn unknown_unit_error() {
        let err = convert(&serde_json::json!({"value": 1.0, "from_unit": "blarg", "to_unit": "meter"}))
            .unwrap_err()
            .to_string();
        assert_eq!(err, "invalid input: unknown unit: blarg");
        assert!(!err.contains("No such unit"), "leaked rink internals: {err}");
    }

    #[test]
    fn list_units_all() {
        let (d, _) = list_units(&serde_json::json!({})).unwrap();
        assert!(d["dimensions"]["length"].is_array());
        assert!(d["dimensions"]["temperature"].is_array());
    }

    #[test]
    fn list_units_filtered() {
        let (d, _) = list_units(&serde_json::json!({"query": "mass"})).unwrap();
        assert!(d["dimensions"]["mass"].is_array());
        assert!(d["dimensions"].get("length").is_none());
    }
}
