//! Golden conformance: the Rust core must rank an identical corpus identically
//! to the Python contract lib (`askfaro_embedded_search`).
//!
//! `golden.json` is generated by `gen_golden.py` from the Python SQLite backend
//! + the deterministic bag-of-words embedder. This test rebuilds the same corpus
//! with the Rust `SqliteBackend` + `BowEmbedder` and asserts every query's ranked
//! `[(object_id, match_type)]` matches. It is the executable form of the
//! library's core promise — "index server-side, retrieve on-device, get the same
//! results" — and the Rust extension of the Python `test_parity.py`.
//!
//! (Embedder parity itself — that the Rust `ort` + EmbeddingGemma pipeline
//! reproduces the Python `onnxruntime` vectors — is covered by the Phase-1 spike
//! at cosine 1.0; this test covers the retrieval + RRF-fusion contract.)

use askfaro_core::search::sqlite::SqliteBackend;
use askfaro_core::search::{BowEmbedder, Filters, IndexDoc, SearchIndex, SearchParams};
use serde::Deserialize;

#[derive(Deserialize)]
struct Golden {
    corpus: Vec<(String, String, String, String, serde_json::Value)>,
    queries: Vec<GoldenQuery>,
}

#[derive(Deserialize)]
struct GoldenQuery {
    query: serde_json::Value,
    ranked: Vec<(String, String)>,
}

#[test]
fn rust_ranks_identically_to_python() {
    let raw = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden.json"))
        .expect("golden.json — run gen_golden.py to (re)generate");
    let golden: Golden = serde_json::from_str(&raw).unwrap();

    let backend = SqliteBackend::open_in_memory(&["default"]).unwrap();
    let index = SearchIndex::new(backend, BowEmbedder::new("default"));

    let docs: Vec<IndexDoc> = golden
        .corpus
        .iter()
        .map(|(otype, oid, title, body, attrs)| {
            let mut d = IndexDoc::leaf(otype, oid, title, body);
            d.attrs = Some(attrs.to_string());
            d
        })
        .collect();
    index.upsert_many(&docs).unwrap();

    for gq in &golden.queries {
        let q = gq.query["query"].as_str().unwrap();

        let mut filters = Filters::default();
        if let Some(types) = gq.query.get("object_types").and_then(|v| v.as_array()) {
            filters.object_types =
                Some(types.iter().map(|t| t.as_str().unwrap().to_string()).collect());
        }
        if let Some(attrs) = gq.query.get("attrs").and_then(|v| v.as_object()) {
            filters.attrs = Some(
                attrs
                    .iter()
                    .map(|(k, v)| (k.clone(), v.as_str().unwrap().to_string()))
                    .collect(),
            );
        }

        let params = SearchParams {
            k: 5,
            filters,
            ..Default::default()
        };
        let got: Vec<(String, String)> = index
            .search(q, &params)
            .unwrap()
            .into_iter()
            .map(|r| (r.object_id, r.match_type.as_str().to_string()))
            .collect();

        assert_eq!(
            got, gq.ranked,
            "ranking diverged for query {q:?}:\n  rust   = {got:?}\n  python = {:?}",
            gq.ranked
        );
    }
}
