//! Emit the free-tool calling contract as JSON, for a host to embed in a prompt.
//!
//! The shapes live in Rust beside the executors, because this crate is the one
//! implementation both paths run: the server's `internal_tools` namespaces call
//! this same code, so a contract published here is true locally and in the cloud
//! by construction. Scope's tool registry is generated by Python, which cannot
//! read Rust, so this prints what that generator embeds and a drift check
//! compares the two.
//!
//! ```sh
//! cargo run --features free-tools --example free_tool_contract
//! ```
use askfaro_core::free_tools;

fn main() {
    let map: serde_json::Map<String, serde_json::Value> = free_tools::describe()
        .into_iter()
        .map(|(name, contract)| {
            // Collapse the source's line continuations to single spaces: this
            // text goes into a tool description, and stray runs of whitespace
            // are tokens paid for on every turn in the cached prefix.
            let flat = contract.split_whitespace().collect::<Vec<_>>().join(" ");
            (name.to_string(), serde_json::Value::String(flat))
        })
        .collect();
    println!("{}", serde_json::to_string_pretty(&map).expect("serialize"));
}
